#!/bin/bash

export JAVA_HOME=/usr/lib/jvm/default-java

STORE_PASSWORD=XXXX

# Get key password 
#read -s -p "Password for certificate store: " STORE_PASSWORD
#echo password = ${STORE_PASSWORD}

KEY_STORE=$JAVA_HOME/lib/security/cacerts

USBDM_PLUGIN_HOME=/home/peter/Documents/Development/usbdm/usbdm-eclipse-plugins
USBDM_UPDATE_SITE=${USBDM_PLUGIN_HOME}/UpdateSite
KEY_ALIAS=JarSigning

echo Deleting self-signed certificate
sudo keytool -delete -alias ${KEY_ALIAS} -cacerts -storepass ${STORE_PASSWORD} -validity 180

echo Generating self-signed certificate
sudo keytool -genkey -alias ${KEY_ALIAS} -cacerts -storepass ${STORE_PASSWORD} -validity 4360 -dname "cn=Peter O'Donoghue, ou=USBDM, o=USBDM, c=AU"

echo List certificates
sudo keytool -list -alias ${KEY_ALIAS} -cacerts -storepass ${STORE_PASSWORD} 

exit

# Sign jars
for f in ${USBDM_UPDATE_SITE}/target/repository/features/*.jar ${USBDM_UPDATE_SITE}/target/repository/plugins/*.jar; do
   echo $f
   echo jarsigner -keystore ${KEY_STORE} -storepass ${STORE_PASSWORD} $f ${KEY_ALIAS}
done
