/**
 * @file      hardware.cpp (generated from MK20D5.usbdmHardware)
 * @version   1.2.0
 * @brief     Pin declarations for FRDM_K20D5
 *
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#include "hardware.h"

namespace USBDM {

/**
 * Used to configure pin-mapping before 1st use of peripherals
 */
void mapAllPins() {
      enablePortClocks(PORTA_CLOCK_MASK|PORTC_CLOCK_MASK|PORTB_CLOCK_MASK|PORTD_CLOCK_MASK|PORTE_CLOCK_MASK);

      ((PORT_Type *)PORTD_BasePtr)->GPCLR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(0)|PORT_GPCLR_GPWE(0x60U);
      ((PORT_Type *)PORTD_BasePtr)->GPCLR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(1)|PORT_GPCLR_GPWE(0x11U);
      ((PORT_Type *)PORTD_BasePtr)->GPCLR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(2)|PORT_GPCLR_GPWE(0xEU);
      ((PORT_Type *)PORTE_BasePtr)->GPCLR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(1)|PORT_GPCLR_GPWE(0x3U);
      ((PORT_Type *)PORTB_BasePtr)->GPCHR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(0)|PORT_GPCHR_GPWE(0xCU);
      ((PORT_Type *)PORTB_BasePtr)->GPCLR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(1)|PORT_GPCLR_GPWE(0xFU);
      ((PORT_Type *)PORTB_BasePtr)->GPCHR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(3)|PORT_GPCHR_GPWE(0x3U);
      ((PORT_Type *)PORTC_BasePtr)->GPCLR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(0)|PORT_GPCLR_GPWE(0x3U);
      ((PORT_Type *)PORTC_BasePtr)->GPCLR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(1)|PORT_GPCLR_GPWE(0xFFCU);
      ((PORT_Type *)PORTA_BasePtr)->GPCHR = USBDM::XTAL_DEFAULT_PCR|PORT_PCR_MUX(0)|PORT_GPCHR_GPWE(0xCU);
      ((PORT_Type *)PORTA_BasePtr)->GPCLR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(1)|PORT_GPCLR_GPWE(0x3036U);
      ((PORT_Type *)PORTA_BasePtr)->GPCLR = USBDM::DEFAULT_PCR|PORT_PCR_MUX(7)|PORT_GPCLR_GPWE(0x9U);
}

} // End namespace USBDM

