/**
 * @file      hardware.cpp (generated from MK20D5.usbdmHardware)
 * @version   1.2.0
 * @brief     Pin declarations for FRDM_K20D5
 *
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#include "hardware.h"

namespace USBDM {

/**
 * Used to configure pin-mapping before 1st use of peripherals
 */
void mapAllPins() {
      enablePortClocks(PORTA_CLOCK_MASK|PORTC_CLOCK_MASK|PORTB_CLOCK_MASK|PORTD_CLOCK_MASK|PORTE_CLOCK_MASK);

      ((PORT_Type *)PORTD_BasePtr)->GPCLR = 0x200|PORT_GPCLR_GPWE(0xEU);
      ((PORT_Type *)PORTD_BasePtr)->GPCLR = 0x100|PORT_GPCLR_GPWE(0x11U);
      ((PORT_Type *)PORTD_BasePtr)->GPCLR = 0x0|PORT_GPCLR_GPWE(0x60U);
      ((PORT_Type *)PORTE_BasePtr)->GPCLR = 0x100|PORT_GPCLR_GPWE(0x2U);
      ((PORT_Type *)PORTB_BasePtr)->GPCLR = 0x8100|PORT_GPCLR_GPWE(0x1U);
      ((PORT_Type *)PORTB_BasePtr)->GPCHR = 0x8000|PORT_GPCHR_GPWE(0xCU);
      ((PORT_Type *)PORTB_BasePtr)->GPCHR = 0x8300|PORT_GPCHR_GPWE(0x3U);
      ((PORT_Type *)PORTC_BasePtr)->GPCLR = 0x100|PORT_GPCLR_GPWE(0x878U);
      ((PORT_Type *)PORTC_BasePtr)->GPCLR = 0x0|PORT_GPCLR_GPWE(0x3U);
      ((PORT_Type *)PORTA_BasePtr)->GPCLR = 0x100|PORT_GPCLR_GPWE(0x2012U);
      ((PORT_Type *)PORTA_BasePtr)->GPCLR = 0x700|PORT_GPCLR_GPWE(0x8U);
      ((PORT_Type *)PORTA_BasePtr)->GPCLR = 0x8700|PORT_GPCLR_GPWE(0x1U);
      ((PORT_Type *)PORTA_BasePtr)->GPCHR = 0x8000|PORT_GPCHR_GPWE(0xCU);
}

} // End namespace USBDM

