/**
 * @file      hardware.cpp (generated from MK66F18.usbdmHardware)
 * @version   1.2.0
 * @brief     Pin declarations for FRDM_K66F
 *
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#include "hardware.h"

namespace USBDM {

struct PinInit {
   uint32_t pcrValue;
   uint32_t volatile *pcr;
};

static constexpr PinInit pinInit[] = {
 /* PTA10      ==> FTM2_CH0                       */  { PORT_PCR_MUX(3)|USBDM::DEFAULT_PCR, &PORTA->PCR[10], },
 /* PTA11      ==> GPIOA_11/LLWU_P23              */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTA->PCR[11], },
 /* PTA25      ==> GPIOA_25                       */  { PORT_PCR_MUX(1)|USBDM::DEFAULT_PCR, &PORTA->PCR[25], },
};

/**
 * Used to configure pin-mapping before 1st use of peripherals
 */
void mapAllPins() {

   SIM->FIXED_PORT_CLOCK_REG |= PORTA_CLOCK_MASK;

   for (const PinInit *p=pinInit; p<(pinInit+(sizeof(pinInit)/sizeof(pinInit[0]))); p++) {
      *(p->pcr) = p->pcrValue;
   }
}

} // End namespace USBDM
