/**
 * @file      pin_mapping.h (derived from MKL43Z4.csv)
 * @version   1.2.0
 * @brief     Pin declarations for MKL43Z256VLH4
 *
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically from Configure.hardware.
 * Any manual changes will be lost.
 */
#ifndef PROJECT_HEADERS_PIN_MAPPING_H
#define PROJECT_HEADERS_PIN_MAPPING_H

#include <stddef.h>
#include "derivative.h"

/*
 * Common Mux settings for PCR
 */
#undef FIXED_ADC_FN            
#undef FIXED_GPIO_FN           
#undef FIXED_PORT_CLOCK_REG    
#define FIXED_ADC_FN             0                    // Fixed ADC Multiplexing value
#define FIXED_GPIO_FN            1                    // Fixed GPIO Multiplexing value
#define FIXED_PORT_CLOCK_REG     SCGC5                // Fixed PORT Clock

/*
 * Peripheral clock macros
 */
#define PORT_CLOCK_REG       SCGC5

namespace USBDM {

/*
 * Peripheral Information Classes
 */
/**
 * @addtogroup 0_Group 0, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End 0_Group
 * @}
 */
/**
 * @addtogroup ADC_Group ADC, Analogue Input
 * @brief Pins used for Analogue Input
 * @{
 */
/**
 * Peripheral information for ADC, Analogue Input
 */
class Adc0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = ADC0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_ADC0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {ADC0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* ADC0_SE0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* ADC0_SE3        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE4b       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE5b       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE6b       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE7b       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE8        = PTB0 (p35)                     */  { PORTB_CLOCK_MASK, PORTB_BasePtr,  GPIOB_BasePtr,  0,   0  },
         /* ADC0_SE9        = PTB1 (p36)                     */  { PORTB_CLOCK_MASK, PORTB_BasePtr,  GPIOB_BasePtr,  1,   0  },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* ADC0_SE11       = PTC2 (p45)                     */  { PORTC_CLOCK_MASK, PORTC_BasePtr,  GPIOC_BasePtr,  2,   0  },
         /* ADC0_SE12       = PTB2 (p37)                     */  { PORTB_CLOCK_MASK, PORTB_BasePtr,  GPIOB_BasePtr,  2,   0  },
         /* ADC0_SE13       = PTB3 (p38)                     */  { PORTB_CLOCK_MASK, PORTB_BasePtr,  GPIOB_BasePtr,  3,   0  },
         /* ADC0_SE14       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE15       = PTC1 (p44)                     */  { PORTC_CLOCK_MASK, PORTC_BasePtr,  GPIOC_BasePtr,  1,   0  },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* ADC0_SE23       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* ADC0_SE4a       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* ADC0_SE7a       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
   class InfoDP {
   public:
      //! Information for each signal of peripheral
      static constexpr PcrInfo  info[] = {
   
            // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
            /* ADC0_DP0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
            /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
            /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
            /* ADC0_DP3        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
      };
   }; 
   class InfoDM {
   public:
      //! Information for each signal of peripheral
      static constexpr PcrInfo  info[] = {
   
            // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
            /* ADC0_DM0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
            /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
            /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
            /* ADC0_DM3        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
      };
   }; 
};

/** 
 * End ADC_Group
 * @}
 */
/**
 * @addtogroup CLKOUT_Group CLKOUT, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End CLKOUT_Group
 * @}
 */
/**
 * @addtogroup CMP_Group CMP, Analogue Comparator
 * @brief Pins used for Analogue Comparator
 * @{
 */
/**
 * Peripheral information for CMP, Analogue Comparator
 */
class Cmp0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = CMP0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_CMP0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {CMP0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* CMP0_IN0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* CMP0_IN1        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* CMP0_IN4        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* CMP0_IN5        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* CMP0_OUT        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End CMP_Group
 * @}
 */
/**
 * @addtogroup DAC_Misc_Group DAC, DAC0 (Miscellaneous)
 * @brief Pins used for DAC0 (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for DAC, DAC0 (Miscellaneous)
 */
class Dac0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = DAC0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_DAC0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 0;

};

/** 
 * End DAC_Misc_Group
 * @}
 */
/**
 * @addtogroup DMA_Misc_Group DMA, DMA0 (Miscellaneous)
 * @brief Pins used for DMA0 (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for DMA, DMA0 (Miscellaneous)
 */
class Dma0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = DMA0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC7_DMA_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC7);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 0;

};

/** 
 * End DMA_Misc_Group
 * @}
 */
/**
 * @addtogroup DMAMUX_Group DMAMUX, Direct Memory Access (DMA)
 * @brief Pins used for Direct Memory Access (DMA)
 * @{
 */
/**
 * Peripheral information for DMAMUX, Direct Memory Access (DMA)
 */
class Dmamux0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = DMAMUX0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_DMAMUX0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 0;

};

/** 
 * End DMAMUX_Group
 * @}
 */
/**
 * @addtogroup EXTRG_Group EXTRG, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End EXTRG_Group
 * @}
 */
/**
 * @addtogroup FLEXIO_Misc_Group FLEXIO, FLEXIO (Miscellaneous)
 * @brief Pins used for FLEXIO (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for FLEXIO, FLEXIO (Miscellaneous)
 */
class FlexioInfo {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = FLEXIO_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_FLEXIO_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {UART2_FLEXIO_IRQn};

};

/** 
 * End FLEXIO_Misc_Group
 * @}
 */
/**
 * @addtogroup FTFE_Misc_Group FTFE, FTFE (Miscellaneous)
 * @brief Pins used for FTFE (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for FTFE, FTFE (Miscellaneous)
 */
class FtfeInfo {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = FTFE_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_FTF_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 0;

};

/** 
 * End FTFE_Misc_Group
 * @}
 */
/**
 * @addtogroup GPIO_Group GPIO, Digital Input/Output
 * @brief Pins used for Digital Input/Output
 * @{
 */
/**
 * Peripheral information for GPIO, Digital Input/Output
 */
class GpioAInfo {
public:
   //! PORT Hardware base pointer
   static constexpr uint32_t pcrAddress   = PORTA_BasePtr;

   //! GPIO Hardware base pointer
   static constexpr uint32_t gpioAddress   = GPIOA_BasePtr;

   //! Value for PCR (including MUX value)
   static constexpr uint32_t pcrValue  = GPIO_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_PORTA_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {PORTA_IRQn};

};

/**
 * Peripheral information for GPIO, Digital Input/Output
 */
class GpioBInfo {
public:
   //! PORT Hardware base pointer
   static constexpr uint32_t pcrAddress   = PORTB_BasePtr;

   //! GPIO Hardware base pointer
   static constexpr uint32_t gpioAddress   = GPIOB_BasePtr;

   //! Value for PCR (including MUX value)
   static constexpr uint32_t pcrValue  = GPIO_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_PORTB_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

};

/**
 * Peripheral information for GPIO, Digital Input/Output
 */
class GpioCInfo {
public:
   //! PORT Hardware base pointer
   static constexpr uint32_t pcrAddress   = PORTC_BasePtr;

   //! GPIO Hardware base pointer
   static constexpr uint32_t gpioAddress   = GPIOC_BasePtr;

   //! Value for PCR (including MUX value)
   static constexpr uint32_t pcrValue  = GPIO_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_PORTC_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {PORTCD_IRQn};

};

/**
 * Peripheral information for GPIO, Digital Input/Output
 */
class GpioDInfo {
public:
   //! PORT Hardware base pointer
   static constexpr uint32_t pcrAddress   = PORTD_BasePtr;

   //! GPIO Hardware base pointer
   static constexpr uint32_t gpioAddress   = GPIOD_BasePtr;

   //! Value for PCR (including MUX value)
   static constexpr uint32_t pcrValue  = GPIO_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_PORTD_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {PORTCD_IRQn};

};

/**
 * Peripheral information for GPIO, Digital Input/Output
 */
class GpioEInfo {
public:
   //! PORT Hardware base pointer
   static constexpr uint32_t pcrAddress   = PORTE_BasePtr;

   //! GPIO Hardware base pointer
   static constexpr uint32_t gpioAddress   = GPIOE_BasePtr;

   //! Value for PCR (including MUX value)
   static constexpr uint32_t pcrValue  = GPIO_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_PORTE_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

};

/** 
 * End GPIO_Group
 * @}
 */
/**
 * @addtogroup I2C_Group I2C, Inter-Integrated-Circuit Interface
 * @brief Pins used for Inter-Integrated-Circuit Interface
 * @{
 */
/**
 * Peripheral information for I2C, Inter-Integrated-Circuit Interface
 */
class I2c0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = I2C0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = I2C_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_I2C0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {I2C0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* I2C0_SCL        = PTE24 (p20)                    */  { PORTE_CLOCK_MASK, PORTE_BasePtr,  GPIOE_BasePtr,  24,  5  },
         /* I2C0_SDA        = PTE25 (p21)                    */  { PORTE_CLOCK_MASK, PORTE_BasePtr,  GPIOE_BasePtr,  25,  5  },
   };
};

/**
 * Peripheral information for I2C, Inter-Integrated-Circuit Interface
 */
class I2c1Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = I2C1_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = I2C_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_I2C1_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {I2C1_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* I2C1_SCL        = PTE1 (p2)                      */  { PORTE_CLOCK_MASK, PORTE_BasePtr,  GPIOE_BasePtr,  1,   6  },
         /* I2C1_SDA        = PTE0 (p1)                      */  { PORTE_CLOCK_MASK, PORTE_BasePtr,  GPIOE_BasePtr,  0,   6  },
   };
};

/** 
 * End I2C_Group
 * @}
 */
/**
 * @addtogroup I2S_Group I2S, Inter-Integrated-Circuit Interface
 * @brief Pins used for Inter-Integrated-Circuit Interface
 * @{
 */
/**
 * Peripheral information for I2S, Inter-Integrated-Circuit Interface
 */
class I2s0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = I2S0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_I2S0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {I2S0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* I2S0_MCLK       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* I2S0_RX_BCLK    = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* I2S0_RX_FS      = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* I2S0_TX_BCLK    = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* I2S0_TX_FS      = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End I2S_Group
 * @}
 */
/**
 * @addtogroup LCD_Misc_Group LCD, LCD (Miscellaneous)
 * @brief Pins used for LCD (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for LCD, LCD (Miscellaneous)
 */
class LcdInfo {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = LCD_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_SLCD_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {LCD_IRQn};

};

/** 
 * End LCD_Misc_Group
 * @}
 */
/**
 * @addtogroup LLWU_Group LLWU, Low-leakage Wake-up Unit
 * @brief Pins used for Low-leakage Wake-up Unit
 * @{
 */
/**
 * Peripheral information for LLWU, Low-leakage Wake-up Unit
 */
class LlwuInfo {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = LLWU_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 0;

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* LLWU_P5         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P6         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P7         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P8         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P9         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P10        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* LLWU_P14        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P15        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End LLWU_Group
 * @}
 */
/**
 * @addtogroup LPTMR_Group LPTMR, Low Power Timer
 * @brief Pins used for Low Power Timer
 * @{
 */
/**
 * Peripheral information for LPTMR, Low Power Timer
 */
class Lptmr0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = LPTMR0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_LPTMR_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {LPTMR0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* LPTMR0_ALT1     = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LPTMR0_ALT2     = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End LPTMR_Group
 * @}
 */
/**
 * @addtogroup LPUART_Group LPUART, Low Power Universal Asynchonous Receiver/Transmitter
 * @brief Pins used for Universal Asynchonous Receiver/Transmitter
 * @{
 */
/**
 * Peripheral information for LPUART, Low Power Universal Asynchonous Receiver/Transmitter
 */
class Lpuart0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = LPUART0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_LPUART0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {LPUART0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* LPUART0_TX      = PTA2 (p24)                     */  { PORTA_CLOCK_MASK, PORTA_BasePtr,  GPIOA_BasePtr,  2,   2  },
         /* LPUART0_RX      = PTA1 (p23)                     */  { PORTA_CLOCK_MASK, PORTA_BasePtr,  GPIOA_BasePtr,  1,   2  },
   };
};

/**
 * Peripheral information for LPUART, Low Power Universal Asynchonous Receiver/Transmitter
 */
class Lpuart1Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = LPUART1_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_LPUART1_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {LPUART1_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* LPUART1_TX      = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LPUART1_RX      = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End LPUART_Group
 * @}
 */
/**
 * @addtogroup NMI_B_Group NMI_b, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End NMI_B_Group
 * @}
 */
/**
 * @addtogroup OSC0_Group OSC0, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End OSC0_Group
 * @}
 */
/**
 * @addtogroup PIT_Group PIT, Programmable Interrupt Timer
 * @brief Pins used for Programmable Interrupt Timer
 * @{
 */
/**
 * Peripheral information for PIT, Programmable Interrupt Timer
 */
class PitInfo {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = PIT_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_PIT_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {PIT_IRQn};

   //! Default value for PIT->SC register
   static constexpr uint32_t pitLoadValue  = 2000;

};

/** 
 * End PIT_Group
 * @}
 */
/**
 * @addtogroup RESET_B_Group RESET_b, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End RESET_B_Group
 * @}
 */
/**
 * @addtogroup RTC_Group RTC, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End RTC_Group
 * @}
 */
/**
 * @addtogroup SPI_Group SPI, Serial Peripheral Interface
 * @brief Pins used for Serial Peripheral Interface
 * @{
 */
/**
 * Peripheral information for SPI, Serial Peripheral Interface
 */
class Spi0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = SPI0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_SPI0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {SPI0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* SPI0_SCK        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI0_MISO       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI0_MOSI       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI0_SS         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

using Spi0_PCS0 = USBDM::PcrTable_T<USBDM::Spi0Info, 3>;
/**
 * Peripheral information for SPI, Serial Peripheral Interface
 */
class Spi1Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = SPI1_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_SPI1_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {SPI1_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* SPI1_SCK        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI1_MISO       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI1_MOSI       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI1_SS         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

using Spi1_PCS0 = USBDM::PcrTable_T<USBDM::Spi1Info, 3>;
/** 
 * End SPI_Group
 * @}
 */
/**
 * @addtogroup SWD_Group SWD, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End SWD_Group
 * @}
 */
/**
 * @addtogroup TPM_Group TPM, PWM, Input capture and Output compare
 * @brief Pins used for PWM, Input capture and Output compare
 * @{
 */
/**
 * Peripheral information for TPM, PWM, Input capture and Output compare
 */
class Tpm0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = TPM0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_TPM0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {TPM0_IRQn};

   //! Default value for tmr->SC register
   static constexpr uint32_t scValue  = TPM_SC_CMOD(1)|TPM_SC_PS(0);

   static constexpr int NUM_CHANNELS  = 6;

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* TPM0_CH0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TPM0_CH1        = PTA4 (p26)                     */  { PORTA_CLOCK_MASK, PORTA_BasePtr,  GPIOA_BasePtr,  4,   3  },
         /* TPM0_CH2        = PTE29 (p17)                    */  { PORTE_CLOCK_MASK, PORTE_BasePtr,  GPIOE_BasePtr,  29,  3  },
         /* TPM0_CH3        = PTD3 (p60)                     */  { PORTD_CLOCK_MASK, PORTD_BasePtr,  GPIOD_BasePtr,  3,   4  },
         /* TPM0_CH4        = PTD4 (p61)                     */  { PORTD_CLOCK_MASK, PORTD_BasePtr,  GPIOD_BasePtr,  4,   4  },
         /* TPM0_CH5        = PTD5 (p62)                     */  { PORTD_CLOCK_MASK, PORTD_BasePtr,  GPIOD_BasePtr,  5,   4  },
   };
};

/**
 * Peripheral information for TPM, PWM, Input capture and Output compare
 */
class Tpm1Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = TPM1_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_TPM1_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {TPM1_IRQn};

   //! Default value for tmr->SC register
   static constexpr uint32_t scValue  = TPM_SC_CMOD(1)|TPM_SC_PS(0);

   static constexpr int NUM_CHANNELS  = 2;

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* TPM1_CH0        = PTA12 (p28)                    */  { PORTA_CLOCK_MASK, PORTA_BasePtr,  GPIOA_BasePtr,  12,  3  },
         /* TPM1_CH1        = PTA13 (p29)                    */  { PORTA_CLOCK_MASK, PORTA_BasePtr,  GPIOA_BasePtr,  13,  3  },
   };
};

/**
 * Peripheral information for TPM, PWM, Input capture and Output compare
 */
class Tpm2Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = TPM2_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_TPM2_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {TPM2_IRQn};

   //! Default value for tmr->SC register
   static constexpr uint32_t scValue  = TPM_SC_CMOD(1)|TPM_SC_PS(0);

   static constexpr int NUM_CHANNELS  = 2;

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* TPM2_CH0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TPM2_CH1        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End TPM_Group
 * @}
 */
/**
 * @addtogroup TPM_CLKIN0_Group TPM_CLKIN0, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End TPM_CLKIN0_Group
 * @}
 */
/**
 * @addtogroup TPM_CLKIN1_Group TPM_CLKIN1, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End TPM_CLKIN1_Group
 * @}
 */
/**
 * @addtogroup UART_Group UART, Universal Asynchonous Receiver/Transmitter
 * @brief Pins used for Universal Asynchonous Receiver/Transmitter
 * @{
 */
/**
 * Peripheral information for UART, Universal Asynchonous Receiver/Transmitter
 */
class Uart2Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = UART2_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_UART2_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {UART2_FLEXIO_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* UART2_TX        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* UART2_RX        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End UART_Group
 * @}
 */
/**
 * @addtogroup USB_Misc_Group USB, USB0 (Miscellaneous)
 * @brief Pins used for USB0 (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for USB, USB0 (Miscellaneous)
 */
class Usb0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = USB0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_USB_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {USB0_IRQn};

};

/** 
 * End USB_Misc_Group
 * @}
 */
/**
 * @addtogroup VCAP1_Group VCAP1, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VCAP1_Group
 * @}
 */
/**
 * @addtogroup VCAP2_Group VCAP2, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VCAP2_Group
 * @}
 */
/**
 * @addtogroup VDD_Misc_Group VDD, VDD (Miscellaneous)
 * @brief Pins used for VDD (Miscellaneous)
 * @{
 */
/** 
 * End VDD_Misc_Group
 * @}
 */
/**
 * @addtogroup VDDA_Group VDDA, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VDDA_Group
 * @}
 */
/**
 * @addtogroup VLL1_Group VLL1, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VLL1_Group
 * @}
 */
/**
 * @addtogroup VLL2_Group VLL2, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VLL2_Group
 * @}
 */
/**
 * @addtogroup VLL3_Group VLL3, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VLL3_Group
 * @}
 */
/**
 * @addtogroup VOUT33_Group VOUT33, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VOUT33_Group
 * @}
 */
/**
 * @addtogroup VREF0_Group VREF0, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VREF0_Group
 * @}
 */
/**
 * @addtogroup VREFH_Group VREFH, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VREFH_Group
 * @}
 */
/**
 * @addtogroup VREFL_Group VREFL, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VREFL_Group
 * @}
 */
/**
 * @addtogroup VREGIN_Group VREGIN, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VREGIN_Group
 * @}
 */
/**
 * @addtogroup VSS_Misc_Group VSS, VSS (Miscellaneous)
 * @brief Pins used for VSS (Miscellaneous)
 * @{
 */
/** 
 * End VSS_Misc_Group
 * @}
 */
/**
 * @addtogroup VSSA_Group VSSA, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VSSA_Group
 * @}
 */

} // End namespace USBDM

#include "gpio_defs.h"

namespace USBDM {

/**
 * @addtogroup ADC_Group ADC, Analogue Input
 * @brief Pins used for Analogue Input
 * @{
 */
/**
 * Convenience templated class representing an ADC
 *
 * Example
 * @code
 *  // Instantiate ADC0 single-ended channel #8
 *  const adc0<8> adc0_se8;
 *
 *  // Initialise ADC
 *  adc0_se8.initialiseADC(USBDM::resolution_12bit_se);
 *
 *  // Set as analogue input
 *  adc0_se8.setAnalogueInput();
 *
 *  // Read input
 *  uint16_t value = adc0_se8.readAnalogue();
 *  @endcode
 *
 * @tparam adcChannel    ADC channel
 */
template<uint8_t channel> using Adc0 = Adc_T<Adc0Info, channel>;

using adc_p35              = const USBDM::Adc0<8>;
using adc_p36              = const USBDM::Adc0<9>;
using adc_p37              = const USBDM::Adc0<12>;
using adc_p38              = const USBDM::Adc0<13>;
using adc_p44              = const USBDM::Adc0<15>;
using adc_p45              = const USBDM::Adc0<11>;
/** 
 * End ADC_Group
 * @}
 */
/**
 * @addtogroup GPIO_Group GPIO, Digital Input/Output
 * @brief Pins used for Digital Input/Output
 * @{
 */
/**
 * @brief Convenience template for GpioA. See @ref Gpio_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 3 of GpioA
 * GpioA<3> GpioA3
 *
 * // Set as digital output
 * GpioA3.setOutput();
 *
 * // Set pin high
 * GpioA3.set();
 *
 * // Set pin low
 * GpioA3.clear();
 *
 * // Toggle pin
 * GpioA3.toggle();
 *
 * // Set pin to boolean value
 * GpioA3.write(true);
 *
 * // Set pin to boolean value
 * GpioA3.write(false);
 *
 * // Set as digital input
 * GpioA3.setInput();
 *
 * // Read pin as boolean value
 * bool x = GpioA3.read();
 * @endcode
 *
 * @tparam bitNum        Bit number in the port
 */
template<uint8_t bitNum> using GpioA = Gpio_T<GpioAInfo, bitNum>;

/**
 * @brief Convenience template for GpioA fields. See @ref Field_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 6 down to 3 of GpioA
 * GpioAField<6,3> GpioA6_3
 *
 * // Set as digital output
 * GpioA6_3.setOutput();
 *
 * // Write value to field
 * GpioA6_3.write(0x53);
 *
 * // Clear all of field
 * GpioA6_3.bitClear();
 *
 * // Clear lower two bits of field
 * GpioA6_3.bitClear(0x3);
 *
 * // Set lower two bits of field
 * GpioA6_3.bitSet(0x3);
 *
 * // Set as digital input
 * GpioA6_3.setInput();
 *
 * // Read pin as int value
 * int x = GpioA6_3.read();
 * @endcode
 *
 * @tparam left          Bit number of leftmost bit in port (inclusive)
 * @tparam right         Bit number of rightmost bit in port (inclusive)
 */
template<int left, int right> using GpioAField = Field_T<GpioAInfo, left, right>;

using gpio_p27             = const USBDM::GpioA<5>;
/**
 * @brief Convenience template for GpioB. See @ref Gpio_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 3 of GpioB
 * GpioB<3> GpioB3
 *
 * // Set as digital output
 * GpioB3.setOutput();
 *
 * // Set pin high
 * GpioB3.set();
 *
 * // Set pin low
 * GpioB3.clear();
 *
 * // Toggle pin
 * GpioB3.toggle();
 *
 * // Set pin to boolean value
 * GpioB3.write(true);
 *
 * // Set pin to boolean value
 * GpioB3.write(false);
 *
 * // Set as digital input
 * GpioB3.setInput();
 *
 * // Read pin as boolean value
 * bool x = GpioB3.read();
 * @endcode
 *
 * @tparam bitNum        Bit number in the port
 */
template<uint8_t bitNum> using GpioB = Gpio_T<GpioBInfo, bitNum>;

/**
 * @brief Convenience template for GpioB fields. See @ref Field_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 6 down to 3 of GpioB
 * GpioBField<6,3> GpioB6_3
 *
 * // Set as digital output
 * GpioB6_3.setOutput();
 *
 * // Write value to field
 * GpioB6_3.write(0x53);
 *
 * // Clear all of field
 * GpioB6_3.bitClear();
 *
 * // Clear lower two bits of field
 * GpioB6_3.bitClear(0x3);
 *
 * // Set lower two bits of field
 * GpioB6_3.bitSet(0x3);
 *
 * // Set as digital input
 * GpioB6_3.setInput();
 *
 * // Read pin as int value
 * int x = GpioB6_3.read();
 * @endcode
 *
 * @tparam left          Bit number of leftmost bit in port (inclusive)
 * @tparam right         Bit number of rightmost bit in port (inclusive)
 */
template<int left, int right> using GpioBField = Field_T<GpioBInfo, left, right>;

/**
 * @brief Convenience template for GpioC. See @ref Gpio_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 3 of GpioC
 * GpioC<3> GpioC3
 *
 * // Set as digital output
 * GpioC3.setOutput();
 *
 * // Set pin high
 * GpioC3.set();
 *
 * // Set pin low
 * GpioC3.clear();
 *
 * // Toggle pin
 * GpioC3.toggle();
 *
 * // Set pin to boolean value
 * GpioC3.write(true);
 *
 * // Set pin to boolean value
 * GpioC3.write(false);
 *
 * // Set as digital input
 * GpioC3.setInput();
 *
 * // Read pin as boolean value
 * bool x = GpioC3.read();
 * @endcode
 *
 * @tparam bitNum        Bit number in the port
 */
template<uint8_t bitNum> using GpioC = Gpio_T<GpioCInfo, bitNum>;

/**
 * @brief Convenience template for GpioC fields. See @ref Field_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 6 down to 3 of GpioC
 * GpioCField<6,3> GpioC6_3
 *
 * // Set as digital output
 * GpioC6_3.setOutput();
 *
 * // Write value to field
 * GpioC6_3.write(0x53);
 *
 * // Clear all of field
 * GpioC6_3.bitClear();
 *
 * // Clear lower two bits of field
 * GpioC6_3.bitClear(0x3);
 *
 * // Set lower two bits of field
 * GpioC6_3.bitSet(0x3);
 *
 * // Set as digital input
 * GpioC6_3.setInput();
 *
 * // Read pin as int value
 * int x = GpioC6_3.read();
 * @endcode
 *
 * @tparam left          Bit number of leftmost bit in port (inclusive)
 * @tparam right         Bit number of rightmost bit in port (inclusive)
 */
template<int left, int right> using GpioCField = Field_T<GpioCInfo, left, right>;

/**
 * @brief Convenience template for GpioD. See @ref Gpio_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 3 of GpioD
 * GpioD<3> GpioD3
 *
 * // Set as digital output
 * GpioD3.setOutput();
 *
 * // Set pin high
 * GpioD3.set();
 *
 * // Set pin low
 * GpioD3.clear();
 *
 * // Toggle pin
 * GpioD3.toggle();
 *
 * // Set pin to boolean value
 * GpioD3.write(true);
 *
 * // Set pin to boolean value
 * GpioD3.write(false);
 *
 * // Set as digital input
 * GpioD3.setInput();
 *
 * // Read pin as boolean value
 * bool x = GpioD3.read();
 * @endcode
 *
 * @tparam bitNum        Bit number in the port
 */
template<uint8_t bitNum> using GpioD = Gpio_T<GpioDInfo, bitNum>;

/**
 * @brief Convenience template for GpioD fields. See @ref Field_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 6 down to 3 of GpioD
 * GpioDField<6,3> GpioD6_3
 *
 * // Set as digital output
 * GpioD6_3.setOutput();
 *
 * // Write value to field
 * GpioD6_3.write(0x53);
 *
 * // Clear all of field
 * GpioD6_3.bitClear();
 *
 * // Clear lower two bits of field
 * GpioD6_3.bitClear(0x3);
 *
 * // Set lower two bits of field
 * GpioD6_3.bitSet(0x3);
 *
 * // Set as digital input
 * GpioD6_3.setInput();
 *
 * // Read pin as int value
 * int x = GpioD6_3.read();
 * @endcode
 *
 * @tparam left          Bit number of leftmost bit in port (inclusive)
 * @tparam right         Bit number of rightmost bit in port (inclusive)
 */
template<int left, int right> using GpioDField = Field_T<GpioDInfo, left, right>;

using gpio_p59             = const USBDM::GpioD<2>;
/**
 * @brief Convenience template for GpioE. See @ref Gpio_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 3 of GpioE
 * GpioE<3> GpioE3
 *
 * // Set as digital output
 * GpioE3.setOutput();
 *
 * // Set pin high
 * GpioE3.set();
 *
 * // Set pin low
 * GpioE3.clear();
 *
 * // Toggle pin
 * GpioE3.toggle();
 *
 * // Set pin to boolean value
 * GpioE3.write(true);
 *
 * // Set pin to boolean value
 * GpioE3.write(false);
 *
 * // Set as digital input
 * GpioE3.setInput();
 *
 * // Read pin as boolean value
 * bool x = GpioE3.read();
 * @endcode
 *
 * @tparam bitNum        Bit number in the port
 */
template<uint8_t bitNum> using GpioE = Gpio_T<GpioEInfo, bitNum>;

/**
 * @brief Convenience template for GpioE fields. See @ref Field_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 6 down to 3 of GpioE
 * GpioEField<6,3> GpioE6_3
 *
 * // Set as digital output
 * GpioE6_3.setOutput();
 *
 * // Write value to field
 * GpioE6_3.write(0x53);
 *
 * // Clear all of field
 * GpioE6_3.bitClear();
 *
 * // Clear lower two bits of field
 * GpioE6_3.bitClear(0x3);
 *
 * // Set lower two bits of field
 * GpioE6_3.bitSet(0x3);
 *
 * // Set as digital input
 * GpioE6_3.setInput();
 *
 * // Read pin as int value
 * int x = GpioE6_3.read();
 * @endcode
 *
 * @tparam left          Bit number of leftmost bit in port (inclusive)
 * @tparam right         Bit number of rightmost bit in port (inclusive)
 */
template<int left, int right> using GpioEField = Field_T<GpioEInfo, left, right>;

using gpio_p18             = const USBDM::GpioE<30>;
using gpio_p19             = const USBDM::GpioE<31>;
/** 
 * End GPIO_Group
 * @}
 */
/**
 * @addtogroup TPM_Group TPM, PWM, Input capture and Output compare
 * @brief Pins used for PWM, Input capture and Output compare
 * @{
 */
/**
 * Convenience template class representing a TPM
 *
 * Example
 * @code
 * // Instantiate the tpm channel (for TPM0 CH6)
 * const USBDM::Tpm0<6>   tpm0_ch6;
 *
 * // Initialise PWM with initial period and alignment
 * tpm0_ch6.setPwmOutput(200, USBDM::ftm_leftAlign);
 *
 * // Change period (in ticks)
 * tpm0_ch6.setPeriod(500);
 *
 * // Change duty cycle (in percent)
 * tpm0_ch6.setDutyCycle(45);
 * @endcode
 *
 * @tparam channel    Timer channel
 */
template<uint8_t channel> using Tpm0 = TmrBase_T<Tpm0Info, channel>;

using tpm_p26              = const USBDM::Tpm0<1>;
using tpm_p60              = const USBDM::Tpm0<3>;
using tpm_p61              = const USBDM::Tpm0<4>;
using tpm_p62              = const USBDM::Tpm0<5>;
using tpm_p17              = const USBDM::Tpm0<2>;
/**
 * Convenience template class representing a TPM
 *
 * Example
 * @code
 * // Instantiate the tpm channel (for TPM0 CH6)
 * const USBDM::Tpm0<6>   tpm0_ch6;
 *
 * // Initialise PWM with initial period and alignment
 * tpm0_ch6.setPwmOutput(200, USBDM::ftm_leftAlign);
 *
 * // Change period (in ticks)
 * tpm0_ch6.setPeriod(500);
 *
 * // Change duty cycle (in percent)
 * tpm0_ch6.setDutyCycle(45);
 * @endcode
 *
 * @tparam channel    Timer channel
 */
template<uint8_t channel> using Tpm1 = TmrBase_T<Tpm1Info, channel>;

using tpm_p28              = const USBDM::Tpm1<0>;
using tpm_p29              = const USBDM::Tpm1<1>;
/**
 * Convenience template class representing a TPM
 *
 * Example
 * @code
 * // Instantiate the tpm channel (for TPM0 CH6)
 * const USBDM::Tpm0<6>   tpm0_ch6;
 *
 * // Initialise PWM with initial period and alignment
 * tpm0_ch6.setPwmOutput(200, USBDM::ftm_leftAlign);
 *
 * // Change period (in ticks)
 * tpm0_ch6.setPeriod(500);
 *
 * // Change duty cycle (in percent)
 * tpm0_ch6.setDutyCycle(45);
 * @endcode
 *
 * @tparam channel    Timer channel
 */
template<uint8_t channel> using Tpm2 = TmrBase_T<Tpm2Info, channel>;

/** 
 * End TPM_Group
 * @}
 */
/**
 * Used to configure pin-mapping before 1st use of peripherals
 */
extern void usbdm_PinMapping();

} // End namespace USBDM
/**
 *
 * @mainpage Summary
 *
 * @section PinsByPinName Pins by Pin Name
 *
 *    Pin Name               |   Functions                                 |  Location           |  Description  
 *  ------------------------ | --------------------------------------------|---------------------| ------------- 
 *  PTA0                     | SWD_CLK                                     | p22                 | -       
 *  PTA1                     | LPUART0_RX                                  | p23                 | -       
 *  PTA2                     | LPUART0_TX                                  | p24                 | -       
 *  PTA3                     | SWD_DIO                                     | p25                 | -       
 *  PTA4                     | TPM0_CH1                                    | p26                 | -       
 *  PTA5                     | GPIOA_5                                     | p27                 | -       
 *  PTA12                    | TPM1_CH0                                    | p28                 | -       
 *  PTA13                    | TPM1_CH1                                    | p29                 | -       
 *  PTA18                    | EXTAL0                                      | p32                 | -       
 *  PTA19                    | XTAL0                                       | p33                 | -       
 *  PTA20                    | RESET_b                                     | p34                 | -       
 *  PTB0                     | LCD_P0/ADC0_SE8                             | p35                 | -       
 *  PTB1                     | LCD_P1/ADC0_SE9                             | p36                 | -       
 *  PTB2                     | LCD_P2/ADC0_SE12                            | p37                 | -       
 *  PTB3                     | LCD_P3/ADC0_SE13                            | p38                 | -       
 *  PTB16                    | LCD_P12                                     | p39                 | -       
 *  PTB17                    | LCD_P13                                     | p40                 | -       
 *  PTB18                    | LCD_P14                                     | p41                 | -       
 *  PTB19                    | LCD_P15                                     | p42                 | -       
 *  PTC0                     | LCD_P20/ADC0_SE14                           | p43                 | -       
 *  PTC1                     | LCD_P21/ADC0_SE15                           | p44                 | -       
 *  PTC2                     | LCD_P22/ADC0_SE11                           | p45                 | -       
 *  PTC3                     | LCD_P23                                     | p46                 | -       
 *  PTC4                     | LCD_P24                                     | p53                 | -       
 *  PTC5                     | LCD_P25                                     | p54                 | -       
 *  PTC6                     | LCD_P26/CMP0_IN0                            | p55                 | -       
 *  PTC7                     | LCD_P27/CMP0_IN1                            | p56                 | -       
 *  PTD0                     | LCD_P40                                     | p57                 | -       
 *  PTD1                     | LCD_P41/ADC0_SE5b                           | p58                 | -       
 *  PTD2                     | GPIOD_2                                     | p59                 | -       
 *  PTD3                     | TPM0_CH3                                    | p60                 | -       
 *  PTD4                     | TPM0_CH4                                    | p61                 | -       
 *  PTD5                     | TPM0_CH5                                    | p62                 | -       
 *  PTD6                     | LCD_P46/ADC0_SE7b                           | p63                 | -       
 *  PTD7                     | LCD_P47                                     | p64                 | -       
 *  PTE0                     | I2C1_SDA                                    | p1                  | -       
 *  PTE1                     | I2C1_SCL                                    | p2                  | -       
 *  PTE20                    | LCD_P59/ADC0_DP0/ADC0_SE0                   | p9                  | -       
 *  PTE21                    | LCD_P60/ADC0_DM0/ADC0_SE4a                  | p10                 | -       
 *  PTE22                    | ADC0_DP3/ADC0_SE3                           | p11                 | -       
 *  PTE23                    | ADC0_DM3/ADC0_SE7a                          | p12                 | -       
 *  PTE24                    | I2C0_SCL                                    | p20                 | -       
 *  PTE25                    | I2C0_SDA                                    | p21                 | -       
 *  PTE29                    | TPM0_CH2                                    | p17                 | -       
 *  PTE30                    | GPIOE_30                                    | p18                 | -       
 *  PTE31                    | GPIOE_31                                    | p19                 | -       
 *  USB0_DM                  | USB0_DM                                     | p6                  | -       
 *  USB0_DP                  | USB0_DP                                     | p5                  | -       
 *  VCAP1                    | VCAP1                                       | p52                 | -       
 *  VCAP2                    | VCAP2                                       | p51                 | -       
 *  VDD1                     | VDD1                                        | p3                  | -       
 *  VDD2                     | VDD2                                        | p30                 | -       
 *  VDDA                     | VDDA                                        | p13                 | -       
 *  VLL1                     | VLL1                                        | p50                 | -       
 *  VLL2                     | VLL2                                        | p49                 | -       
 *  VLL3                     | VLL3                                        | p48                 | -       
 *  VOUT33                   | VOUT33                                      | p7                  | -       
 *  VREFH                    | VREFH                                       | p14                 | -       
 *  VREFL                    | VREFL                                       | p15                 | -       
 *  VREGIN                   | VREGIN                                      | p8                  | -       
 *  VSS1                     | VSS1                                        | p4                  | -       
 *  VSS2                     | VSS2                                        | p31                 | -       
 *  VSS3                     | VSS3                                        | p47                 | -       
 *  VSSA                     | VSSA                                        | p16                 | -       
 *
 *
 * @section PinsByLocation Pins by Location
 *
 *    Pin Name               |   Functions                                 |  Location           |  Description  
 *  ------------------------ | --------------------------------------------|---------------------| ------------- 
 *  PTE0                     | I2C1_SDA                                    | p1                  | -       
 *  PTE1                     | I2C1_SCL                                    | p2                  | -       
 *  VDD1                     | VDD1                                        | p3                  | -       
 *  VSS1                     | VSS1                                        | p4                  | -       
 *  USB0_DP                  | USB0_DP                                     | p5                  | -       
 *  USB0_DM                  | USB0_DM                                     | p6                  | -       
 *  VOUT33                   | VOUT33                                      | p7                  | -       
 *  VREGIN                   | VREGIN                                      | p8                  | -       
 *  PTE20                    | LCD_P59/ADC0_DP0/ADC0_SE0                   | p9                  | -       
 *  PTE21                    | LCD_P60/ADC0_DM0/ADC0_SE4a                  | p10                 | -       
 *  PTE22                    | ADC0_DP3/ADC0_SE3                           | p11                 | -       
 *  PTE23                    | ADC0_DM3/ADC0_SE7a                          | p12                 | -       
 *  VDDA                     | VDDA                                        | p13                 | -       
 *  VREFH                    | VREFH                                       | p14                 | -       
 *  VREFL                    | VREFL                                       | p15                 | -       
 *  VSSA                     | VSSA                                        | p16                 | -       
 *  PTE29                    | TPM0_CH2                                    | p17                 | -       
 *  PTE30                    | GPIOE_30                                    | p18                 | -       
 *  PTE31                    | GPIOE_31                                    | p19                 | -       
 *  PTE24                    | I2C0_SCL                                    | p20                 | -       
 *  PTE25                    | I2C0_SDA                                    | p21                 | -       
 *  PTA0                     | SWD_CLK                                     | p22                 | -       
 *  PTA1                     | LPUART0_RX                                  | p23                 | -       
 *  PTA2                     | LPUART0_TX                                  | p24                 | -       
 *  PTA3                     | SWD_DIO                                     | p25                 | -       
 *  PTA4                     | TPM0_CH1                                    | p26                 | -       
 *  PTA5                     | GPIOA_5                                     | p27                 | -       
 *  PTA12                    | TPM1_CH0                                    | p28                 | -       
 *  PTA13                    | TPM1_CH1                                    | p29                 | -       
 *  VDD2                     | VDD2                                        | p30                 | -       
 *  VSS2                     | VSS2                                        | p31                 | -       
 *  PTA18                    | EXTAL0                                      | p32                 | -       
 *  PTA19                    | XTAL0                                       | p33                 | -       
 *  PTA20                    | RESET_b                                     | p34                 | -       
 *  PTB0                     | LCD_P0/ADC0_SE8                             | p35                 | -       
 *  PTB1                     | LCD_P1/ADC0_SE9                             | p36                 | -       
 *  PTB2                     | LCD_P2/ADC0_SE12                            | p37                 | -       
 *  PTB3                     | LCD_P3/ADC0_SE13                            | p38                 | -       
 *  PTB16                    | LCD_P12                                     | p39                 | -       
 *  PTB17                    | LCD_P13                                     | p40                 | -       
 *  PTB18                    | LCD_P14                                     | p41                 | -       
 *  PTB19                    | LCD_P15                                     | p42                 | -       
 *  PTC0                     | LCD_P20/ADC0_SE14                           | p43                 | -       
 *  PTC1                     | LCD_P21/ADC0_SE15                           | p44                 | -       
 *  PTC2                     | LCD_P22/ADC0_SE11                           | p45                 | -       
 *  PTC3                     | LCD_P23                                     | p46                 | -       
 *  VSS3                     | VSS3                                        | p47                 | -       
 *  VLL3                     | VLL3                                        | p48                 | -       
 *  VLL2                     | VLL2                                        | p49                 | -       
 *  VLL1                     | VLL1                                        | p50                 | -       
 *  VCAP2                    | VCAP2                                       | p51                 | -       
 *  VCAP1                    | VCAP1                                       | p52                 | -       
 *  PTC4                     | LCD_P24                                     | p53                 | -       
 *  PTC5                     | LCD_P25                                     | p54                 | -       
 *  PTC6                     | LCD_P26/CMP0_IN0                            | p55                 | -       
 *  PTC7                     | LCD_P27/CMP0_IN1                            | p56                 | -       
 *  PTD0                     | LCD_P40                                     | p57                 | -       
 *  PTD1                     | LCD_P41/ADC0_SE5b                           | p58                 | -       
 *  PTD2                     | GPIOD_2                                     | p59                 | -       
 *  PTD3                     | TPM0_CH3                                    | p60                 | -       
 *  PTD4                     | TPM0_CH4                                    | p61                 | -       
 *  PTD5                     | TPM0_CH5                                    | p62                 | -       
 *  PTD6                     | LCD_P46/ADC0_SE7b                           | p63                 | -       
 *  PTD7                     | LCD_P47                                     | p64                 | -       
 *
 *
 * @section PinsByFunction Pins by Function
 *
 *    Pin Name               |   Functions                                 |  Location           |  Description  
 *  ------------------------ | --------------------------------------------|---------------------| ------------- 
 *  PTE23                    | ADC0_DM3/ADC0_SE7a                          | p12                 | -       
 *  PTE22                    | ADC0_DP3/ADC0_SE3                           | p11                 | -       
 *  PTA18                    | EXTAL0                                      | p32                 | -       
 *  PTA5                     | GPIOA_5                                     | p27                 | -       
 *  PTD2                     | GPIOD_2                                     | p59                 | -       
 *  PTE30                    | GPIOE_30                                    | p18                 | -       
 *  PTE31                    | GPIOE_31                                    | p19                 | -       
 *  PTE24                    | I2C0_SCL                                    | p20                 | -       
 *  PTE25                    | I2C0_SDA                                    | p21                 | -       
 *  PTE1                     | I2C1_SCL                                    | p2                  | -       
 *  PTE0                     | I2C1_SDA                                    | p1                  | -       
 *  PTB0                     | LCD_P0/ADC0_SE8                             | p35                 | -       
 *  PTB1                     | LCD_P1/ADC0_SE9                             | p36                 | -       
 *  PTB2                     | LCD_P2/ADC0_SE12                            | p37                 | -       
 *  PTB3                     | LCD_P3/ADC0_SE13                            | p38                 | -       
 *  PTB16                    | LCD_P12                                     | p39                 | -       
 *  PTB17                    | LCD_P13                                     | p40                 | -       
 *  PTB18                    | LCD_P14                                     | p41                 | -       
 *  PTB19                    | LCD_P15                                     | p42                 | -       
 *  PTC0                     | LCD_P20/ADC0_SE14                           | p43                 | -       
 *  PTC1                     | LCD_P21/ADC0_SE15                           | p44                 | -       
 *  PTC2                     | LCD_P22/ADC0_SE11                           | p45                 | -       
 *  PTC3                     | LCD_P23                                     | p46                 | -       
 *  PTC4                     | LCD_P24                                     | p53                 | -       
 *  PTC5                     | LCD_P25                                     | p54                 | -       
 *  PTC6                     | LCD_P26/CMP0_IN0                            | p55                 | -       
 *  PTC7                     | LCD_P27/CMP0_IN1                            | p56                 | -       
 *  PTD0                     | LCD_P40                                     | p57                 | -       
 *  PTD1                     | LCD_P41/ADC0_SE5b                           | p58                 | -       
 *  PTD6                     | LCD_P46/ADC0_SE7b                           | p63                 | -       
 *  PTD7                     | LCD_P47                                     | p64                 | -       
 *  PTE20                    | LCD_P59/ADC0_DP0/ADC0_SE0                   | p9                  | -       
 *  PTE21                    | LCD_P60/ADC0_DM0/ADC0_SE4a                  | p10                 | -       
 *  PTA1                     | LPUART0_RX                                  | p23                 | -       
 *  PTA2                     | LPUART0_TX                                  | p24                 | -       
 *  PTA20                    | RESET_b                                     | p34                 | -       
 *  PTA0                     | SWD_CLK                                     | p22                 | -       
 *  PTA3                     | SWD_DIO                                     | p25                 | -       
 *  PTA4                     | TPM0_CH1                                    | p26                 | -       
 *  PTE29                    | TPM0_CH2                                    | p17                 | -       
 *  PTD3                     | TPM0_CH3                                    | p60                 | -       
 *  PTD4                     | TPM0_CH4                                    | p61                 | -       
 *  PTD5                     | TPM0_CH5                                    | p62                 | -       
 *  PTA12                    | TPM1_CH0                                    | p28                 | -       
 *  PTA13                    | TPM1_CH1                                    | p29                 | -       
 *  USB0_DM                  | USB0_DM                                     | p6                  | -       
 *  USB0_DP                  | USB0_DP                                     | p5                  | -       
 *  VCAP1                    | VCAP1                                       | p52                 | -       
 *  VCAP2                    | VCAP2                                       | p51                 | -       
 *  VDD1                     | VDD1                                        | p3                  | -       
 *  VDD2                     | VDD2                                        | p30                 | -       
 *  VDDA                     | VDDA                                        | p13                 | -       
 *  VLL1                     | VLL1                                        | p50                 | -       
 *  VLL2                     | VLL2                                        | p49                 | -       
 *  VLL3                     | VLL3                                        | p48                 | -       
 *  VOUT33                   | VOUT33                                      | p7                  | -       
 *  VREFH                    | VREFH                                       | p14                 | -       
 *  VREFL                    | VREFL                                       | p15                 | -       
 *  VREGIN                   | VREGIN                                      | p8                  | -       
 *  VSS1                     | VSS1                                        | p4                  | -       
 *  VSS2                     | VSS2                                        | p31                 | -       
 *  VSS3                     | VSS3                                        | p47                 | -       
 *  VSSA                     | VSSA                                        | p16                 | -       
 *  PTA19                    | XTAL0                                       | p33                 | -       
 *
 */

#endif /* PROJECT_HEADERS_PIN_MAPPING_H */
