/**
 * @file      pin_mapping.h (derived from MKL46Z4.csv)
 * @version   1.2.0
 * @brief     Pin declarations for MKL46Z256VLL4
 *
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically from Configure.hardware.
 * Any manual changes will be lost.
 */
#ifndef PROJECT_HEADERS_PIN_MAPPING_H
#define PROJECT_HEADERS_PIN_MAPPING_H

#include <stddef.h>
#include "derivative.h"

/*
 * Common Mux settings for PCR
 */
#undef FIXED_ADC_FN            
#undef FIXED_GPIO_FN           
#undef FIXED_PORT_CLOCK_REG    
#define FIXED_ADC_FN             0                    // Fixed ADC Multiplexing value
#define FIXED_GPIO_FN            1                    // Fixed GPIO Multiplexing value
#define FIXED_PORT_CLOCK_REG     SCGC5                // Fixed PORT Clock

/*
 * Peripheral clock macros
 */
#define PORT_CLOCK_REG       SCGC5

namespace USBDM {

/*
 * Peripheral Information Classes
 */
/**
 * @addtogroup 0_Group 0, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End 0_Group
 * @}
 */
/**
 * @addtogroup ADC_Group ADC, Analogue Input
 * @brief Pins used for Analogue Input
 * @{
 */
/**
 * Peripheral information for ADC, Analogue Input
 */
class Adc0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = ADC0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_ADC0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {ADC0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* ADC0_SE0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE1        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE2        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE3        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE4b       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE5b       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE6b       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE7b       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE8        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE9        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* ADC0_SE11       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE12       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE13       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE14       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE15       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* ADC0_SE23       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* ADC0_SE4a       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE5a       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE6a       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* ADC0_SE7a       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
   class InfoDP {
   public:
      //! Information for each signal of peripheral
      static constexpr PcrInfo  info[] = {
   
            // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
            /* ADC0_DP0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
            /* ADC0_DP1        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
            /* ADC0_DP2        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
            /* ADC0_DP3        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
      };
   }; 
   class InfoDM {
   public:
      //! Information for each signal of peripheral
      static constexpr PcrInfo  info[] = {
   
            // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
            /* ADC0_DM0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
            /* ADC0_DM1        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
            /* ADC0_DM2        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
            /* ADC0_DM3        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
      };
   }; 
};

/** 
 * End ADC_Group
 * @}
 */
/**
 * @addtogroup CLKOUT_Group CLKOUT, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End CLKOUT_Group
 * @}
 */
/**
 * @addtogroup CMP_Group CMP, Analogue Comparator
 * @brief Pins used for Analogue Comparator
 * @{
 */
/**
 * Peripheral information for CMP, Analogue Comparator
 */
class Cmp0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = CMP0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_CMP_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {CMP0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* CMP0_IN0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* CMP0_IN1        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* CMP0_IN2        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* CMP0_IN3        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* CMP0_IN4        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* CMP0_IN5        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* CMP0_OUT        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End CMP_Group
 * @}
 */
/**
 * @addtogroup DAC_Misc_Group DAC, DAC0 (Miscellaneous)
 * @brief Pins used for DAC0 (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for DAC, DAC0 (Miscellaneous)
 */
class Dac0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = DAC0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_DAC0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {DAC0_IRQn};

};

/** 
 * End DAC_Misc_Group
 * @}
 */
/**
 * @addtogroup DMA_Misc_Group DMA, DMA0 (Miscellaneous)
 * @brief Pins used for DMA0 (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for DMA, DMA0 (Miscellaneous)
 */
class Dma0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = DMA0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC7_DMA_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC7);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 0;

};

/** 
 * End DMA_Misc_Group
 * @}
 */
/**
 * @addtogroup DMAMUX_Group DMAMUX, Direct Memory Access (DMA)
 * @brief Pins used for Direct Memory Access (DMA)
 * @{
 */
/**
 * Peripheral information for DMAMUX, Direct Memory Access (DMA)
 */
class Dmamux0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = DMAMUX0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_DMAMUX0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 0;

};

/** 
 * End DMAMUX_Group
 * @}
 */
/**
 * @addtogroup EXTRG_Group EXTRG, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End EXTRG_Group
 * @}
 */
/**
 * @addtogroup FTFE_Misc_Group FTFE, FTFE (Miscellaneous)
 * @brief Pins used for FTFE (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for FTFE, FTFE (Miscellaneous)
 */
class FtfeInfo {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = FTFE_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_FTF_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 0;

};

/** 
 * End FTFE_Misc_Group
 * @}
 */
/**
 * @addtogroup GPIO_Group GPIO, Digital Input/Output
 * @brief Pins used for Digital Input/Output
 * @{
 */
/**
 * Peripheral information for GPIO, Digital Input/Output
 */
class GpioAInfo {
public:
   //! PORT Hardware base pointer
   static constexpr uint32_t pcrAddress   = PORTA_BasePtr;

   //! GPIO Hardware base pointer
   static constexpr uint32_t gpioAddress   = GPIOA_BasePtr;

   //! Value for PCR (including MUX value)
   static constexpr uint32_t pcrValue  = GPIO_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_PORTA_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {PORTA_IRQn};

};

/**
 * Peripheral information for GPIO, Digital Input/Output
 */
class GpioBInfo {
public:
   //! PORT Hardware base pointer
   static constexpr uint32_t pcrAddress   = PORTB_BasePtr;

   //! GPIO Hardware base pointer
   static constexpr uint32_t gpioAddress   = GPIOB_BasePtr;

   //! Value for PCR (including MUX value)
   static constexpr uint32_t pcrValue  = GPIO_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_PORTB_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

};

/**
 * Peripheral information for GPIO, Digital Input/Output
 */
class GpioCInfo {
public:
   //! PORT Hardware base pointer
   static constexpr uint32_t pcrAddress   = PORTC_BasePtr;

   //! GPIO Hardware base pointer
   static constexpr uint32_t gpioAddress   = GPIOC_BasePtr;

   //! Value for PCR (including MUX value)
   static constexpr uint32_t pcrValue  = GPIO_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_PORTC_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {PORTCD_IRQn};

};

/**
 * Peripheral information for GPIO, Digital Input/Output
 */
class GpioDInfo {
public:
   //! PORT Hardware base pointer
   static constexpr uint32_t pcrAddress   = PORTD_BasePtr;

   //! GPIO Hardware base pointer
   static constexpr uint32_t gpioAddress   = GPIOD_BasePtr;

   //! Value for PCR (including MUX value)
   static constexpr uint32_t pcrValue  = GPIO_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_PORTD_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {PORTCD_IRQn};

};

/**
 * Peripheral information for GPIO, Digital Input/Output
 */
class GpioEInfo {
public:
   //! PORT Hardware base pointer
   static constexpr uint32_t pcrAddress   = PORTE_BasePtr;

   //! GPIO Hardware base pointer
   static constexpr uint32_t gpioAddress   = GPIOE_BasePtr;

   //! Value for PCR (including MUX value)
   static constexpr uint32_t pcrValue  = GPIO_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_PORTE_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

};

/** 
 * End GPIO_Group
 * @}
 */
/**
 * @addtogroup I2C_Group I2C, Inter-Integrated-Circuit Interface
 * @brief Pins used for Inter-Integrated-Circuit Interface
 * @{
 */
/**
 * Peripheral information for I2C, Inter-Integrated-Circuit Interface
 */
class I2c0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = I2C0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = I2C_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_I2C0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {I2C0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* I2C0_SCL        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* I2C0_SDA        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/**
 * Peripheral information for I2C, Inter-Integrated-Circuit Interface
 */
class I2c1Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = I2C1_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = I2C_DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_I2C1_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {I2C1_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* I2C1_SCL        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* I2C1_SDA        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End I2C_Group
 * @}
 */
/**
 * @addtogroup I2S_Group I2S, Inter-Integrated-Circuit Interface
 * @brief Pins used for Inter-Integrated-Circuit Interface
 * @{
 */
/**
 * Peripheral information for I2S, Inter-Integrated-Circuit Interface
 */
class I2s0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = I2S0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_I2S0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {I2S0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* I2S0_MCLK       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* I2S0_RX_BCLK    = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* I2S0_RX_FS      = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* I2S0_TX_BCLK    = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* I2S0_TX_FS      = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End I2S_Group
 * @}
 */
/**
 * @addtogroup LCD_Misc_Group LCD, LCD (Miscellaneous)
 * @brief Pins used for LCD (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for LCD, LCD (Miscellaneous)
 */
class LcdInfo {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = LCD_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_SLCD_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {LCD_IRQn};

};

/** 
 * End LCD_Misc_Group
 * @}
 */
/**
 * @addtogroup LLWU_Group LLWU, Low-leakage Wake-up Unit
 * @brief Pins used for Low-leakage Wake-up Unit
 * @{
 */
/**
 * Peripheral information for LLWU, Low-leakage Wake-up Unit
 */
class LlwuInfo {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = LLWU_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 0;

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* LLWU_P5         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P6         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P7         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P8         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P9         = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P10        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* LLWU_P14        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LLWU_P15        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End LLWU_Group
 * @}
 */
/**
 * @addtogroup LPTMR_Group LPTMR, Low Power Timer
 * @brief Pins used for Low Power Timer
 * @{
 */
/**
 * Peripheral information for LPTMR, Low Power Timer
 */
class Lptmr0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = LPTMR0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC5_LPTMR_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC5);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {LPTMR0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* --              = --                             */  { 0, 0, 0, INVALID_PCR,  0 },
         /* LPTMR0_ALT1     = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LPTMR0_ALT2     = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* LPTMR0_ALT3     = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End LPTMR_Group
 * @}
 */
/**
 * @addtogroup NMI_B_Group NMI_b, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End NMI_B_Group
 * @}
 */
/**
 * @addtogroup OSC0_Group OSC0, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End OSC0_Group
 * @}
 */
/**
 * @addtogroup PIT_Group PIT, Programmable Interrupt Timer
 * @brief Pins used for Programmable Interrupt Timer
 * @{
 */
/**
 * Peripheral information for PIT, Programmable Interrupt Timer
 */
class PitInfo {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = PIT_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_PIT_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {PIT_IRQn};

   //! Default value for PIT->SC register
   static constexpr uint32_t pitLoadValue  = 2000;

};

/** 
 * End PIT_Group
 * @}
 */
/**
 * @addtogroup RESET_B_Group RESET_b, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End RESET_B_Group
 * @}
 */
/**
 * @addtogroup RTC_Group RTC, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End RTC_Group
 * @}
 */
/**
 * @addtogroup SPI_Group SPI, Serial Peripheral Interface
 * @brief Pins used for Serial Peripheral Interface
 * @{
 */
/**
 * Peripheral information for SPI, Serial Peripheral Interface
 */
class Spi0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = SPI0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_SPI0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {SPI0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* SPI0_SCK        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI0_MISO       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI0_MOSI       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI0_PCS0       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

using Spi0_PCS0 = USBDM::PcrTable_T<USBDM::Spi0Info, 3>;
/**
 * Peripheral information for SPI, Serial Peripheral Interface
 */
class Spi1Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = SPI1_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_SPI1_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {SPI1_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* SPI1_SCK        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI1_MISO       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI1_MOSI       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* SPI1_PCS0       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

using Spi1_PCS0 = USBDM::PcrTable_T<USBDM::Spi1Info, 3>;
/** 
 * End SPI_Group
 * @}
 */
/**
 * @addtogroup SWD_Group SWD, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End SWD_Group
 * @}
 */
/**
 * @addtogroup TPM_Group TPM, PWM, Input capture and Output compare
 * @brief Pins used for PWM, Input capture and Output compare
 * @{
 */
/**
 * Peripheral information for TPM, PWM, Input capture and Output compare
 */
class Tpm0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = TPM0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_TPM0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {TPM0_IRQn};

   //! Default value for tmr->SC register
   static constexpr uint32_t scValue  = TPM_SC_CMOD(1)|TPM_SC_PS(0);

   static constexpr int NUM_CHANNELS  = 6;

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* TPM0_CH0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TPM0_CH1        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TPM0_CH2        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TPM0_CH3        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TPM0_CH4        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TPM0_CH5        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/**
 * Peripheral information for TPM, PWM, Input capture and Output compare
 */
class Tpm1Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = TPM1_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_TPM1_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {TPM1_IRQn};

   //! Default value for tmr->SC register
   static constexpr uint32_t scValue  = TPM_SC_CMOD(1)|TPM_SC_PS(0);

   static constexpr int NUM_CHANNELS  = 2;

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* TPM1_CH0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TPM1_CH1        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/**
 * Peripheral information for TPM, PWM, Input capture and Output compare
 */
class Tpm2Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = TPM2_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC6_TPM2_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC6);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {TPM2_IRQn};

   //! Default value for tmr->SC register
   static constexpr uint32_t scValue  = TPM_SC_CMOD(1)|TPM_SC_PS(0);

   static constexpr int NUM_CHANNELS  = 2;

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* TPM2_CH0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TPM2_CH1        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End TPM_Group
 * @}
 */
/**
 * @addtogroup TPM_CLKIN0_Group TPM_CLKIN0, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End TPM_CLKIN0_Group
 * @}
 */
/**
 * @addtogroup TPM_CLKIN1_Group TPM_CLKIN1, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End TPM_CLKIN1_Group
 * @}
 */
/**
 * @addtogroup TSI_Group TSI, Misc
 * @brief Pins used for Misc
 * @{
 */
/**
 * Peripheral information for TSI, Low-leakage Wake-up Unit
 */
class Tsi0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = TSI0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 0;

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* TSI0_CH0        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH1        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH2        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH3        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH4        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH5        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH6        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH7        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH8        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH9        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH10       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH11       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH12       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH13       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH14       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* TSI0_CH15       = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End TSI_Group
 * @}
 */
/**
 * @addtogroup UART_Group UART, Universal Asynchonous Receiver/Transmitter
 * @brief Pins used for Universal Asynchonous Receiver/Transmitter
 * @{
 */
/**
 * Peripheral information for UART, Universal Asynchonous Receiver/Transmitter
 */
class Uart0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = UART0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_UART0_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {UART0_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* UART0_TX        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* UART0_RX        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/**
 * Peripheral information for UART, Universal Asynchonous Receiver/Transmitter
 */
class Uart1Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = UART1_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_UART1_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {UART1_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* UART1_TX        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* UART1_RX        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/**
 * Peripheral information for UART, Universal Asynchonous Receiver/Transmitter
 */
class Uart2Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = UART2_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_UART2_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {UART2_IRQn};

   //! Information for each signal of peripheral
   static constexpr PcrInfo  info[] = {

         // Signal            Pin                                 clockMask          pcrAddress      gpioAddress     bit  mux
         /* UART2_TX        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
         /* UART2_RX        = --                             */  { 0, 0, 0, UNMAPPED_PCR, 0 },
   };
};

/** 
 * End UART_Group
 * @}
 */
/**
 * @addtogroup USB_Misc_Group USB, USB0 (Miscellaneous)
 * @brief Pins used for USB0 (Miscellaneous)
 * @{
 */
/**
 * Peripheral information for USB, USB0 (Miscellaneous)
 */
class Usb0Info {
public:
   //! Hardware base pointer
   static constexpr uint32_t basePtr   = USB0_BasePtr;

   //! Base value for PCR (excluding MUX value)
   static constexpr uint32_t pcrValue  = DEFAULT_PCR;

   //! Clock mask for peripheral
   static constexpr uint32_t clockMask = SIM_SCGC4_USB_MASK;

   //! Address of clock register for peripheral
   static constexpr uint32_t clockReg  = SIM_BasePtr+offsetof(SIM_Type,SCGC4);

   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = 1;

   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = {USB0_IRQn};

};

/** 
 * End USB_Misc_Group
 * @}
 */
/**
 * @addtogroup VCAP1_Group VCAP1, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VCAP1_Group
 * @}
 */
/**
 * @addtogroup VCAP2_Group VCAP2, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VCAP2_Group
 * @}
 */
/**
 * @addtogroup VDD_Misc_Group VDD, VDD (Miscellaneous)
 * @brief Pins used for VDD (Miscellaneous)
 * @{
 */
/** 
 * End VDD_Misc_Group
 * @}
 */
/**
 * @addtogroup VDDA_Group VDDA, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VDDA_Group
 * @}
 */
/**
 * @addtogroup VLL1_Group VLL1, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VLL1_Group
 * @}
 */
/**
 * @addtogroup VLL2_Group VLL2, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VLL2_Group
 * @}
 */
/**
 * @addtogroup VLL3_Group VLL3, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VLL3_Group
 * @}
 */
/**
 * @addtogroup VOUT33_Group VOUT33, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VOUT33_Group
 * @}
 */
/**
 * @addtogroup VREFH_Group VREFH, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VREFH_Group
 * @}
 */
/**
 * @addtogroup VREFL_Group VREFL, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VREFL_Group
 * @}
 */
/**
 * @addtogroup VREGIN_Group VREGIN, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VREGIN_Group
 * @}
 */
/**
 * @addtogroup VSS_Misc_Group VSS, VSS (Miscellaneous)
 * @brief Pins used for VSS (Miscellaneous)
 * @{
 */
/** 
 * End VSS_Misc_Group
 * @}
 */
/**
 * @addtogroup VSS1A_Group VSS1a, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VSS1A_Group
 * @}
 */
/**
 * @addtogroup VSSA_Group VSSA, Misc
 * @brief Pins used for Misc
 * @{
 */
/** 
 * End VSSA_Group
 * @}
 */

} // End namespace USBDM

#include "gpio_defs.h"

namespace USBDM {

/**
 * @addtogroup ADC_Group ADC, Analogue Input
 * @brief Pins used for Analogue Input
 * @{
 */
/**
 * Convenience templated class representing an ADC
 *
 * Example
 * @code
 *  // Instantiate ADC0 single-ended channel #8
 *  const adc0<8> adc0_se8;
 *
 *  // Initialise ADC
 *  adc0_se8.initialiseADC(USBDM::resolution_12bit_se);
 *
 *  // Set as analogue input
 *  adc0_se8.setAnalogueInput();
 *
 *  // Read input
 *  uint16_t value = adc0_se8.readAnalogue();
 *  @endcode
 *
 * @tparam adcChannel    ADC channel
 */
template<uint8_t channel> using Adc0 = Adc_T<Adc0Info, channel>;

/** 
 * End ADC_Group
 * @}
 */
/**
 * @addtogroup GPIO_Group GPIO, Digital Input/Output
 * @brief Pins used for Digital Input/Output
 * @{
 */
/**
 * @brief Convenience template for GpioA. See @ref Gpio_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 3 of GpioA
 * GpioA<3> GpioA3
 *
 * // Set as digital output
 * GpioA3.setOutput();
 *
 * // Set pin high
 * GpioA3.set();
 *
 * // Set pin low
 * GpioA3.clear();
 *
 * // Toggle pin
 * GpioA3.toggle();
 *
 * // Set pin to boolean value
 * GpioA3.write(true);
 *
 * // Set pin to boolean value
 * GpioA3.write(false);
 *
 * // Set as digital input
 * GpioA3.setInput();
 *
 * // Read pin as boolean value
 * bool x = GpioA3.read();
 * @endcode
 *
 * @tparam bitNum        Bit number in the port
 */
template<uint8_t bitNum> using GpioA = Gpio_T<GpioAInfo, bitNum>;

/**
 * @brief Convenience template for GpioA fields. See @ref Field_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 6 down to 3 of GpioA
 * GpioAField<6,3> GpioA6_3
 *
 * // Set as digital output
 * GpioA6_3.setOutput();
 *
 * // Write value to field
 * GpioA6_3.write(0x53);
 *
 * // Clear all of field
 * GpioA6_3.bitClear();
 *
 * // Clear lower two bits of field
 * GpioA6_3.bitClear(0x3);
 *
 * // Set lower two bits of field
 * GpioA6_3.bitSet(0x3);
 *
 * // Set as digital input
 * GpioA6_3.setInput();
 *
 * // Read pin as int value
 * int x = GpioA6_3.read();
 * @endcode
 *
 * @tparam left          Bit number of leftmost bit in port (inclusive)
 * @tparam right         Bit number of rightmost bit in port (inclusive)
 */
template<int left, int right> using GpioAField = Field_T<GpioAInfo, left, right>;

/**
 * @brief Convenience template for GpioB. See @ref Gpio_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 3 of GpioB
 * GpioB<3> GpioB3
 *
 * // Set as digital output
 * GpioB3.setOutput();
 *
 * // Set pin high
 * GpioB3.set();
 *
 * // Set pin low
 * GpioB3.clear();
 *
 * // Toggle pin
 * GpioB3.toggle();
 *
 * // Set pin to boolean value
 * GpioB3.write(true);
 *
 * // Set pin to boolean value
 * GpioB3.write(false);
 *
 * // Set as digital input
 * GpioB3.setInput();
 *
 * // Read pin as boolean value
 * bool x = GpioB3.read();
 * @endcode
 *
 * @tparam bitNum        Bit number in the port
 */
template<uint8_t bitNum> using GpioB = Gpio_T<GpioBInfo, bitNum>;

/**
 * @brief Convenience template for GpioB fields. See @ref Field_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 6 down to 3 of GpioB
 * GpioBField<6,3> GpioB6_3
 *
 * // Set as digital output
 * GpioB6_3.setOutput();
 *
 * // Write value to field
 * GpioB6_3.write(0x53);
 *
 * // Clear all of field
 * GpioB6_3.bitClear();
 *
 * // Clear lower two bits of field
 * GpioB6_3.bitClear(0x3);
 *
 * // Set lower two bits of field
 * GpioB6_3.bitSet(0x3);
 *
 * // Set as digital input
 * GpioB6_3.setInput();
 *
 * // Read pin as int value
 * int x = GpioB6_3.read();
 * @endcode
 *
 * @tparam left          Bit number of leftmost bit in port (inclusive)
 * @tparam right         Bit number of rightmost bit in port (inclusive)
 */
template<int left, int right> using GpioBField = Field_T<GpioBInfo, left, right>;

/**
 * @brief Convenience template for GpioC. See @ref Gpio_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 3 of GpioC
 * GpioC<3> GpioC3
 *
 * // Set as digital output
 * GpioC3.setOutput();
 *
 * // Set pin high
 * GpioC3.set();
 *
 * // Set pin low
 * GpioC3.clear();
 *
 * // Toggle pin
 * GpioC3.toggle();
 *
 * // Set pin to boolean value
 * GpioC3.write(true);
 *
 * // Set pin to boolean value
 * GpioC3.write(false);
 *
 * // Set as digital input
 * GpioC3.setInput();
 *
 * // Read pin as boolean value
 * bool x = GpioC3.read();
 * @endcode
 *
 * @tparam bitNum        Bit number in the port
 */
template<uint8_t bitNum> using GpioC = Gpio_T<GpioCInfo, bitNum>;

/**
 * @brief Convenience template for GpioC fields. See @ref Field_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 6 down to 3 of GpioC
 * GpioCField<6,3> GpioC6_3
 *
 * // Set as digital output
 * GpioC6_3.setOutput();
 *
 * // Write value to field
 * GpioC6_3.write(0x53);
 *
 * // Clear all of field
 * GpioC6_3.bitClear();
 *
 * // Clear lower two bits of field
 * GpioC6_3.bitClear(0x3);
 *
 * // Set lower two bits of field
 * GpioC6_3.bitSet(0x3);
 *
 * // Set as digital input
 * GpioC6_3.setInput();
 *
 * // Read pin as int value
 * int x = GpioC6_3.read();
 * @endcode
 *
 * @tparam left          Bit number of leftmost bit in port (inclusive)
 * @tparam right         Bit number of rightmost bit in port (inclusive)
 */
template<int left, int right> using GpioCField = Field_T<GpioCInfo, left, right>;

/**
 * @brief Convenience template for GpioD. See @ref Gpio_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 3 of GpioD
 * GpioD<3> GpioD3
 *
 * // Set as digital output
 * GpioD3.setOutput();
 *
 * // Set pin high
 * GpioD3.set();
 *
 * // Set pin low
 * GpioD3.clear();
 *
 * // Toggle pin
 * GpioD3.toggle();
 *
 * // Set pin to boolean value
 * GpioD3.write(true);
 *
 * // Set pin to boolean value
 * GpioD3.write(false);
 *
 * // Set as digital input
 * GpioD3.setInput();
 *
 * // Read pin as boolean value
 * bool x = GpioD3.read();
 * @endcode
 *
 * @tparam bitNum        Bit number in the port
 */
template<uint8_t bitNum> using GpioD = Gpio_T<GpioDInfo, bitNum>;

/**
 * @brief Convenience template for GpioD fields. See @ref Field_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 6 down to 3 of GpioD
 * GpioDField<6,3> GpioD6_3
 *
 * // Set as digital output
 * GpioD6_3.setOutput();
 *
 * // Write value to field
 * GpioD6_3.write(0x53);
 *
 * // Clear all of field
 * GpioD6_3.bitClear();
 *
 * // Clear lower two bits of field
 * GpioD6_3.bitClear(0x3);
 *
 * // Set lower two bits of field
 * GpioD6_3.bitSet(0x3);
 *
 * // Set as digital input
 * GpioD6_3.setInput();
 *
 * // Read pin as int value
 * int x = GpioD6_3.read();
 * @endcode
 *
 * @tparam left          Bit number of leftmost bit in port (inclusive)
 * @tparam right         Bit number of rightmost bit in port (inclusive)
 */
template<int left, int right> using GpioDField = Field_T<GpioDInfo, left, right>;

/**
 * @brief Convenience template for GpioE. See @ref Gpio_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 3 of GpioE
 * GpioE<3> GpioE3
 *
 * // Set as digital output
 * GpioE3.setOutput();
 *
 * // Set pin high
 * GpioE3.set();
 *
 * // Set pin low
 * GpioE3.clear();
 *
 * // Toggle pin
 * GpioE3.toggle();
 *
 * // Set pin to boolean value
 * GpioE3.write(true);
 *
 * // Set pin to boolean value
 * GpioE3.write(false);
 *
 * // Set as digital input
 * GpioE3.setInput();
 *
 * // Read pin as boolean value
 * bool x = GpioE3.read();
 * @endcode
 *
 * @tparam bitNum        Bit number in the port
 */
template<uint8_t bitNum> using GpioE = Gpio_T<GpioEInfo, bitNum>;

/**
 * @brief Convenience template for GpioE fields. See @ref Field_T
 *
 * <b>Usage</b>
 * @code
 * // Instantiate for bit 6 down to 3 of GpioE
 * GpioEField<6,3> GpioE6_3
 *
 * // Set as digital output
 * GpioE6_3.setOutput();
 *
 * // Write value to field
 * GpioE6_3.write(0x53);
 *
 * // Clear all of field
 * GpioE6_3.bitClear();
 *
 * // Clear lower two bits of field
 * GpioE6_3.bitClear(0x3);
 *
 * // Set lower two bits of field
 * GpioE6_3.bitSet(0x3);
 *
 * // Set as digital input
 * GpioE6_3.setInput();
 *
 * // Read pin as int value
 * int x = GpioE6_3.read();
 * @endcode
 *
 * @tparam left          Bit number of leftmost bit in port (inclusive)
 * @tparam right         Bit number of rightmost bit in port (inclusive)
 */
template<int left, int right> using GpioEField = Field_T<GpioEInfo, left, right>;

/** 
 * End GPIO_Group
 * @}
 */
/**
 * @addtogroup TPM_Group TPM, PWM, Input capture and Output compare
 * @brief Pins used for PWM, Input capture and Output compare
 * @{
 */
/**
 * Convenience template class representing a TPM
 *
 * Example
 * @code
 * // Instantiate the tpm channel (for TPM0 CH6)
 * const USBDM::Tpm0<6>   tpm0_ch6;
 *
 * // Initialise PWM with initial period and alignment
 * tpm0_ch6.setPwmOutput(200, USBDM::ftm_leftAlign);
 *
 * // Change period (in ticks)
 * tpm0_ch6.setPeriod(500);
 *
 * // Change duty cycle (in percent)
 * tpm0_ch6.setDutyCycle(45);
 * @endcode
 *
 * @tparam channel    Timer channel
 */
template<uint8_t channel> using Tpm0 = TmrBase_T<Tpm0Info, channel>;

/**
 * Convenience template class representing a TPM
 *
 * Example
 * @code
 * // Instantiate the tpm channel (for TPM0 CH6)
 * const USBDM::Tpm0<6>   tpm0_ch6;
 *
 * // Initialise PWM with initial period and alignment
 * tpm0_ch6.setPwmOutput(200, USBDM::ftm_leftAlign);
 *
 * // Change period (in ticks)
 * tpm0_ch6.setPeriod(500);
 *
 * // Change duty cycle (in percent)
 * tpm0_ch6.setDutyCycle(45);
 * @endcode
 *
 * @tparam channel    Timer channel
 */
template<uint8_t channel> using Tpm1 = TmrBase_T<Tpm1Info, channel>;

/**
 * Convenience template class representing a TPM
 *
 * Example
 * @code
 * // Instantiate the tpm channel (for TPM0 CH6)
 * const USBDM::Tpm0<6>   tpm0_ch6;
 *
 * // Initialise PWM with initial period and alignment
 * tpm0_ch6.setPwmOutput(200, USBDM::ftm_leftAlign);
 *
 * // Change period (in ticks)
 * tpm0_ch6.setPeriod(500);
 *
 * // Change duty cycle (in percent)
 * tpm0_ch6.setDutyCycle(45);
 * @endcode
 *
 * @tparam channel    Timer channel
 */
template<uint8_t channel> using Tpm2 = TmrBase_T<Tpm2Info, channel>;

/** 
 * End TPM_Group
 * @}
 */
/**
 * Used to configure pin-mapping before 1st use of peripherals
 */
extern void usbdm_PinMapping();

} // End namespace USBDM
/**
 *
 * @mainpage Summary
 *
 * @section PinsByPinName Pins by Pin Name
 *
 *    Pin Name               |   Functions                                 |  Location           |  Description  
 *  ------------------------ | --------------------------------------------|---------------------| ------------- 
 *  PTA0                     | SWD_CLK                                     | p34                 | -       
 *  PTA1                     | TSI0_CH2                                    | p35                 | -       
 *  PTA2                     | TSI0_CH3                                    | p36                 | -       
 *  PTA3                     | SWD_DIO                                     | p37                 | -       
 *  PTA4                     | NMI_b                                       | p38                 | -       
 *  PTA5                     | Disabled                                    | p39                 | -       
 *  PTA6                     | Disabled                                    | p40                 | -       
 *  PTA7                     | Disabled                                    | p41                 | -       
 *  PTA12                    | Disabled                                    | p42                 | -       
 *  PTA13                    | Disabled                                    | p43                 | -       
 *  PTA14                    | Disabled                                    | p44                 | -       
 *  PTA15                    | Disabled                                    | p45                 | -       
 *  PTA16                    | Disabled                                    | p46                 | -       
 *  PTA17                    | Disabled                                    | p47                 | -       
 *  PTA18                    | EXTAL0                                      | p50                 | -       
 *  PTA19                    | XTAL0                                       | p51                 | -       
 *  PTA20                    | RESET_b                                     | p52                 | -       
 *  PTB0                     | LCD_P0/ADC0_SE8/TSI0_CH0                    | p53                 | -       
 *  PTB1                     | LCD_P1/ADC0_SE9/TSI0_CH6                    | p54                 | -       
 *  PTB2                     | LCD_P2/ADC0_SE12/TSI0_CH7                   | p55                 | -       
 *  PTB3                     | LCD_P3/ADC0_SE13/TSI0_CH8                   | p56                 | -       
 *  PTB7                     | LCD_P7                                      | p57                 | -       
 *  PTB8                     | LCD_P8                                      | p58                 | -       
 *  PTB9                     | LCD_P9                                      | p59                 | -       
 *  PTB10                    | LCD_P10                                     | p60                 | -       
 *  PTB11                    | LCD_P11                                     | p61                 | -       
 *  PTB16                    | LCD_P12/TSI0_CH9                            | p62                 | -       
 *  PTB17                    | LCD_P13/TSI0_CH10                           | p63                 | -       
 *  PTB18                    | LCD_P14/TSI0_CH11                           | p64                 | -       
 *  PTB19                    | LCD_P15/TSI0_CH12                           | p65                 | -       
 *  PTB20                    | LCD_P16                                     | p66                 | -       
 *  PTB21                    | LCD_P17                                     | p67                 | -       
 *  PTB22                    | LCD_P18                                     | p68                 | -       
 *  PTB23                    | LCD_P19                                     | p69                 | -       
 *  PTC0                     | LCD_P20/ADC0_SE14/TSI0_CH13                 | p70                 | -       
 *  PTC1                     | LCD_P21/ADC0_SE15/TSI0_CH14                 | p71                 | -       
 *  PTC2                     | LCD_P22/ADC0_SE11/TSI0_CH15                 | p72                 | -       
 *  PTC3                     | LCD_P23                                     | p73                 | -       
 *  PTC4                     | LCD_P24                                     | p80                 | -       
 *  PTC5                     | LCD_P25                                     | p81                 | -       
 *  PTC6                     | LCD_P26/CMP0_IN0                            | p82                 | -       
 *  PTC7                     | LCD_P27/CMP0_IN1                            | p83                 | -       
 *  PTC8                     | LCD_P28/CMP0_IN2                            | p84                 | -       
 *  PTC9                     | LCD_P29/CMP0_IN3                            | p85                 | -       
 *  PTC10                    | LCD_P30                                     | p86                 | -       
 *  PTC11                    | LCD_P31                                     | p87                 | -       
 *  PTC12                    | LCD_P32                                     | p88                 | -       
 *  PTC13                    | LCD_P33                                     | p89                 | -       
 *  PTC16                    | LCD_P36                                     | p90                 | -       
 *  PTC17                    | LCD_P37                                     | p91                 | -       
 *  PTC18                    | LCD_P38                                     | p92                 | -       
 *  PTD0                     | LCD_P40                                     | p93                 | -       
 *  PTD1                     | LCD_P41/ADC0_SE5b                           | p94                 | -       
 *  PTD2                     | LCD_P42                                     | p95                 | -       
 *  PTD3                     | LCD_P43                                     | p96                 | -       
 *  PTD4                     | LCD_P44                                     | p97                 | -       
 *  PTD5                     | LCD_P45/ADC0_SE6b                           | p98                 | -       
 *  PTD6                     | LCD_P46/ADC0_SE7b                           | p99                 | -       
 *  PTD7                     | LCD_P47                                     | p100                | -       
 *  PTE0                     | LCD_P48                                     | p1                  | -       
 *  PTE1                     | LCD_P49                                     | p2                  | -       
 *  PTE2                     | LCD_P50                                     | p3                  | -       
 *  PTE3                     | LCD_P51                                     | p4                  | -       
 *  PTE4                     | LCD_P52                                     | p5                  | -       
 *  PTE5                     | LCD_P53                                     | p6                  | -       
 *  PTE6                     | LCD_P54                                     | p7                  | -       
 *  PTE16                    | LCD_P55/ADC0_DP1/ADC0_SE1                   | p14                 | -       
 *  PTE17                    | LCD_P56/ADC0_DM1/ADC0_SE5a                  | p15                 | -       
 *  PTE18                    | LCD_P57/ADC0_DP2/ADC0_SE2                   | p16                 | -       
 *  PTE19                    | LCD_P58/ADC0_DM2/ADC0_SE6a                  | p17                 | -       
 *  PTE20                    | LCD_P59/ADC0_DP0/ADC0_SE0                   | p18                 | -       
 *  PTE21                    | LCD_P60/ADC0_DM0/ADC0_SE4a                  | p19                 | -       
 *  PTE22                    | ADC0_DP3/ADC0_SE3                           | p20                 | -       
 *  PTE23                    | ADC0_DM3/ADC0_SE7a                          | p21                 | -       
 *  PTE24                    | Disabled                                    | p31                 | -       
 *  PTE25                    | Disabled                                    | p32                 | -       
 *  PTE26                    | Disabled                                    | p33                 | -       
 *  PTE29                    | CMP0_IN5/ADC0_SE4b                          | p26                 | -       
 *  PTE30                    | DAC0_OUT/ADC0_SE23/CMP0_IN4                 | p27                 | -       
 *  PTE31                    | Disabled                                    | p28                 | -       
 *  USB0_DM                  | USB0_DM                                     | p11                 | -       
 *  USB0_DP                  | USB0_DP                                     | p10                 | -       
 *  VCAP1                    | VCAP1/LCD_P39                               | p79                 | -       
 *  VCAP2                    | VCAP2/LCD_P6                                | p78                 | -       
 *  VDD1                     | VDD1                                        | p8                  | -       
 *  VDD2                     | VDD2                                        | p30                 | -       
 *  VDD4                     | VDD4                                        | p48                 | -       
 *  VDDA                     | VDDA                                        | p22                 | -       
 *  VLL1                     | VLL1/LCD_P5                                 | p77                 | -       
 *  VLL2                     | VLL2/LCD_P4                                 | p76                 | -       
 *  VLL3                     | VLL3                                        | p75                 | -       
 *  VOUT33                   | VOUT33                                      | p12                 | -       
 *  VREFH                    | VREFH                                       | p23                 | -       
 *  VREFL                    | VREFL                                       | p24                 | -       
 *  VREGIN                   | VREGIN                                      | p13                 | -       
 *  VSS1                     | VSS1                                        | p9                  | -       
 *  VSS2                     | VSS2                                        | p29                 | -       
 *  VSS4                     | VSS4                                        | p49                 | -       
 *  VSS5                     | VSS5                                        | p74                 | -       
 *  VSSA                     | VSSA                                        | p25                 | -       
 *
 *
 * @section PinsByLocation Pins by Location
 *
 *    Pin Name               |   Functions                                 |  Location           |  Description  
 *  ------------------------ | --------------------------------------------|---------------------| ------------- 
 *  PTE0                     | LCD_P48                                     | p1                  | -       
 *  PTE1                     | LCD_P49                                     | p2                  | -       
 *  PTE2                     | LCD_P50                                     | p3                  | -       
 *  PTE3                     | LCD_P51                                     | p4                  | -       
 *  PTE4                     | LCD_P52                                     | p5                  | -       
 *  PTE5                     | LCD_P53                                     | p6                  | -       
 *  PTE6                     | LCD_P54                                     | p7                  | -       
 *  VDD1                     | VDD1                                        | p8                  | -       
 *  VSS1                     | VSS1                                        | p9                  | -       
 *  USB0_DP                  | USB0_DP                                     | p10                 | -       
 *  USB0_DM                  | USB0_DM                                     | p11                 | -       
 *  VOUT33                   | VOUT33                                      | p12                 | -       
 *  VREGIN                   | VREGIN                                      | p13                 | -       
 *  PTE16                    | LCD_P55/ADC0_DP1/ADC0_SE1                   | p14                 | -       
 *  PTE17                    | LCD_P56/ADC0_DM1/ADC0_SE5a                  | p15                 | -       
 *  PTE18                    | LCD_P57/ADC0_DP2/ADC0_SE2                   | p16                 | -       
 *  PTE19                    | LCD_P58/ADC0_DM2/ADC0_SE6a                  | p17                 | -       
 *  PTE20                    | LCD_P59/ADC0_DP0/ADC0_SE0                   | p18                 | -       
 *  PTE21                    | LCD_P60/ADC0_DM0/ADC0_SE4a                  | p19                 | -       
 *  PTE22                    | ADC0_DP3/ADC0_SE3                           | p20                 | -       
 *  PTE23                    | ADC0_DM3/ADC0_SE7a                          | p21                 | -       
 *  VDDA                     | VDDA                                        | p22                 | -       
 *  VREFH                    | VREFH                                       | p23                 | -       
 *  VREFL                    | VREFL                                       | p24                 | -       
 *  VSSA                     | VSSA                                        | p25                 | -       
 *  PTE29                    | CMP0_IN5/ADC0_SE4b                          | p26                 | -       
 *  PTE30                    | DAC0_OUT/ADC0_SE23/CMP0_IN4                 | p27                 | -       
 *  PTE31                    | Disabled                                    | p28                 | -       
 *  VSS2                     | VSS2                                        | p29                 | -       
 *  VDD2                     | VDD2                                        | p30                 | -       
 *  PTE24                    | Disabled                                    | p31                 | -       
 *  PTE25                    | Disabled                                    | p32                 | -       
 *  PTE26                    | Disabled                                    | p33                 | -       
 *  PTA0                     | SWD_CLK                                     | p34                 | -       
 *  PTA1                     | TSI0_CH2                                    | p35                 | -       
 *  PTA2                     | TSI0_CH3                                    | p36                 | -       
 *  PTA3                     | SWD_DIO                                     | p37                 | -       
 *  PTA4                     | NMI_b                                       | p38                 | -       
 *  PTA5                     | Disabled                                    | p39                 | -       
 *  PTA6                     | Disabled                                    | p40                 | -       
 *  PTA7                     | Disabled                                    | p41                 | -       
 *  PTA12                    | Disabled                                    | p42                 | -       
 *  PTA13                    | Disabled                                    | p43                 | -       
 *  PTA14                    | Disabled                                    | p44                 | -       
 *  PTA15                    | Disabled                                    | p45                 | -       
 *  PTA16                    | Disabled                                    | p46                 | -       
 *  PTA17                    | Disabled                                    | p47                 | -       
 *  VDD4                     | VDD4                                        | p48                 | -       
 *  VSS4                     | VSS4                                        | p49                 | -       
 *  PTA18                    | EXTAL0                                      | p50                 | -       
 *  PTA19                    | XTAL0                                       | p51                 | -       
 *  PTA20                    | RESET_b                                     | p52                 | -       
 *  PTB0                     | LCD_P0/ADC0_SE8/TSI0_CH0                    | p53                 | -       
 *  PTB1                     | LCD_P1/ADC0_SE9/TSI0_CH6                    | p54                 | -       
 *  PTB2                     | LCD_P2/ADC0_SE12/TSI0_CH7                   | p55                 | -       
 *  PTB3                     | LCD_P3/ADC0_SE13/TSI0_CH8                   | p56                 | -       
 *  PTB7                     | LCD_P7                                      | p57                 | -       
 *  PTB8                     | LCD_P8                                      | p58                 | -       
 *  PTB9                     | LCD_P9                                      | p59                 | -       
 *  PTB10                    | LCD_P10                                     | p60                 | -       
 *  PTB11                    | LCD_P11                                     | p61                 | -       
 *  PTB16                    | LCD_P12/TSI0_CH9                            | p62                 | -       
 *  PTB17                    | LCD_P13/TSI0_CH10                           | p63                 | -       
 *  PTB18                    | LCD_P14/TSI0_CH11                           | p64                 | -       
 *  PTB19                    | LCD_P15/TSI0_CH12                           | p65                 | -       
 *  PTB20                    | LCD_P16                                     | p66                 | -       
 *  PTB21                    | LCD_P17                                     | p67                 | -       
 *  PTB22                    | LCD_P18                                     | p68                 | -       
 *  PTB23                    | LCD_P19                                     | p69                 | -       
 *  PTC0                     | LCD_P20/ADC0_SE14/TSI0_CH13                 | p70                 | -       
 *  PTC1                     | LCD_P21/ADC0_SE15/TSI0_CH14                 | p71                 | -       
 *  PTC2                     | LCD_P22/ADC0_SE11/TSI0_CH15                 | p72                 | -       
 *  PTC3                     | LCD_P23                                     | p73                 | -       
 *  VSS5                     | VSS5                                        | p74                 | -       
 *  VLL3                     | VLL3                                        | p75                 | -       
 *  VLL2                     | VLL2/LCD_P4                                 | p76                 | -       
 *  VLL1                     | VLL1/LCD_P5                                 | p77                 | -       
 *  VCAP2                    | VCAP2/LCD_P6                                | p78                 | -       
 *  VCAP1                    | VCAP1/LCD_P39                               | p79                 | -       
 *  PTC4                     | LCD_P24                                     | p80                 | -       
 *  PTC5                     | LCD_P25                                     | p81                 | -       
 *  PTC6                     | LCD_P26/CMP0_IN0                            | p82                 | -       
 *  PTC7                     | LCD_P27/CMP0_IN1                            | p83                 | -       
 *  PTC8                     | LCD_P28/CMP0_IN2                            | p84                 | -       
 *  PTC9                     | LCD_P29/CMP0_IN3                            | p85                 | -       
 *  PTC10                    | LCD_P30                                     | p86                 | -       
 *  PTC11                    | LCD_P31                                     | p87                 | -       
 *  PTC12                    | LCD_P32                                     | p88                 | -       
 *  PTC13                    | LCD_P33                                     | p89                 | -       
 *  PTC16                    | LCD_P36                                     | p90                 | -       
 *  PTC17                    | LCD_P37                                     | p91                 | -       
 *  PTC18                    | LCD_P38                                     | p92                 | -       
 *  PTD0                     | LCD_P40                                     | p93                 | -       
 *  PTD1                     | LCD_P41/ADC0_SE5b                           | p94                 | -       
 *  PTD2                     | LCD_P42                                     | p95                 | -       
 *  PTD3                     | LCD_P43                                     | p96                 | -       
 *  PTD4                     | LCD_P44                                     | p97                 | -       
 *  PTD5                     | LCD_P45/ADC0_SE6b                           | p98                 | -       
 *  PTD6                     | LCD_P46/ADC0_SE7b                           | p99                 | -       
 *  PTD7                     | LCD_P47                                     | p100                | -       
 *
 *
 * @section PinsByFunction Pins by Function
 *
 *    Pin Name               |   Functions                                 |  Location           |  Description  
 *  ------------------------ | --------------------------------------------|---------------------| ------------- 
 *  PTE23                    | ADC0_DM3/ADC0_SE7a                          | p21                 | -       
 *  PTE22                    | ADC0_DP3/ADC0_SE3                           | p20                 | -       
 *  PTE29                    | CMP0_IN5/ADC0_SE4b                          | p26                 | -       
 *  PTE30                    | DAC0_OUT/ADC0_SE23/CMP0_IN4                 | p27                 | -       
 *  PTE31                    | Disabled                                    | p28                 | -       
 *  PTA18                    | EXTAL0                                      | p50                 | -       
 *  PTB0                     | LCD_P0/ADC0_SE8/TSI0_CH0                    | p53                 | -       
 *  PTB1                     | LCD_P1/ADC0_SE9/TSI0_CH6                    | p54                 | -       
 *  PTB2                     | LCD_P2/ADC0_SE12/TSI0_CH7                   | p55                 | -       
 *  PTB3                     | LCD_P3/ADC0_SE13/TSI0_CH8                   | p56                 | -       
 *  PTB7                     | LCD_P7                                      | p57                 | -       
 *  PTB8                     | LCD_P8                                      | p58                 | -       
 *  PTB9                     | LCD_P9                                      | p59                 | -       
 *  PTB10                    | LCD_P10                                     | p60                 | -       
 *  PTB11                    | LCD_P11                                     | p61                 | -       
 *  PTB16                    | LCD_P12/TSI0_CH9                            | p62                 | -       
 *  PTB17                    | LCD_P13/TSI0_CH10                           | p63                 | -       
 *  PTB18                    | LCD_P14/TSI0_CH11                           | p64                 | -       
 *  PTB19                    | LCD_P15/TSI0_CH12                           | p65                 | -       
 *  PTB20                    | LCD_P16                                     | p66                 | -       
 *  PTB21                    | LCD_P17                                     | p67                 | -       
 *  PTB22                    | LCD_P18                                     | p68                 | -       
 *  PTB23                    | LCD_P19                                     | p69                 | -       
 *  PTC0                     | LCD_P20/ADC0_SE14/TSI0_CH13                 | p70                 | -       
 *  PTC1                     | LCD_P21/ADC0_SE15/TSI0_CH14                 | p71                 | -       
 *  PTC2                     | LCD_P22/ADC0_SE11/TSI0_CH15                 | p72                 | -       
 *  PTC3                     | LCD_P23                                     | p73                 | -       
 *  PTC4                     | LCD_P24                                     | p80                 | -       
 *  PTC5                     | LCD_P25                                     | p81                 | -       
 *  PTC6                     | LCD_P26/CMP0_IN0                            | p82                 | -       
 *  PTC7                     | LCD_P27/CMP0_IN1                            | p83                 | -       
 *  PTC8                     | LCD_P28/CMP0_IN2                            | p84                 | -       
 *  PTC9                     | LCD_P29/CMP0_IN3                            | p85                 | -       
 *  PTC10                    | LCD_P30                                     | p86                 | -       
 *  PTC11                    | LCD_P31                                     | p87                 | -       
 *  PTC12                    | LCD_P32                                     | p88                 | -       
 *  PTC13                    | LCD_P33                                     | p89                 | -       
 *  PTC16                    | LCD_P36                                     | p90                 | -       
 *  PTC17                    | LCD_P37                                     | p91                 | -       
 *  PTC18                    | LCD_P38                                     | p92                 | -       
 *  PTD0                     | LCD_P40                                     | p93                 | -       
 *  PTD1                     | LCD_P41/ADC0_SE5b                           | p94                 | -       
 *  PTD2                     | LCD_P42                                     | p95                 | -       
 *  PTD3                     | LCD_P43                                     | p96                 | -       
 *  PTD4                     | LCD_P44                                     | p97                 | -       
 *  PTD5                     | LCD_P45/ADC0_SE6b                           | p98                 | -       
 *  PTD6                     | LCD_P46/ADC0_SE7b                           | p99                 | -       
 *  PTD7                     | LCD_P47                                     | p100                | -       
 *  PTE0                     | LCD_P48                                     | p1                  | -       
 *  PTE1                     | LCD_P49                                     | p2                  | -       
 *  PTE2                     | LCD_P50                                     | p3                  | -       
 *  PTE3                     | LCD_P51                                     | p4                  | -       
 *  PTE4                     | LCD_P52                                     | p5                  | -       
 *  PTE5                     | LCD_P53                                     | p6                  | -       
 *  PTE6                     | LCD_P54                                     | p7                  | -       
 *  PTE16                    | LCD_P55/ADC0_DP1/ADC0_SE1                   | p14                 | -       
 *  PTE17                    | LCD_P56/ADC0_DM1/ADC0_SE5a                  | p15                 | -       
 *  PTE18                    | LCD_P57/ADC0_DP2/ADC0_SE2                   | p16                 | -       
 *  PTE19                    | LCD_P58/ADC0_DM2/ADC0_SE6a                  | p17                 | -       
 *  PTE20                    | LCD_P59/ADC0_DP0/ADC0_SE0                   | p18                 | -       
 *  PTE21                    | LCD_P60/ADC0_DM0/ADC0_SE4a                  | p19                 | -       
 *  PTA4                     | NMI_b                                       | p38                 | -       
 *  PTA20                    | RESET_b                                     | p52                 | -       
 *  PTA0                     | SWD_CLK                                     | p34                 | -       
 *  PTA3                     | SWD_DIO                                     | p37                 | -       
 *  PTA1                     | TSI0_CH2                                    | p35                 | -       
 *  PTA2                     | TSI0_CH3                                    | p36                 | -       
 *  USB0_DM                  | USB0_DM                                     | p11                 | -       
 *  USB0_DP                  | USB0_DP                                     | p10                 | -       
 *  VCAP1                    | VCAP1/LCD_P39                               | p79                 | -       
 *  VCAP2                    | VCAP2/LCD_P6                                | p78                 | -       
 *  VDD1                     | VDD1                                        | p8                  | -       
 *  VDD2                     | VDD2                                        | p30                 | -       
 *  VDD4                     | VDD4                                        | p48                 | -       
 *  VDDA                     | VDDA                                        | p22                 | -       
 *  VLL1                     | VLL1/LCD_P5                                 | p77                 | -       
 *  VLL2                     | VLL2/LCD_P4                                 | p76                 | -       
 *  VLL3                     | VLL3                                        | p75                 | -       
 *  VOUT33                   | VOUT33                                      | p12                 | -       
 *  VREFH                    | VREFH                                       | p23                 | -       
 *  VREFL                    | VREFL                                       | p24                 | -       
 *  VREGIN                   | VREGIN                                      | p13                 | -       
 *  VSS1                     | VSS1                                        | p9                  | -       
 *  VSS2                     | VSS2                                        | p29                 | -       
 *  VSS4                     | VSS4                                        | p49                 | -       
 *  VSS5                     | VSS5                                        | p74                 | -       
 *  VSSA                     | VSSA                                        | p25                 | -       
 *  PTA19                    | XTAL0                                       | p51                 | -       
 *
 */

#endif /* PROJECT_HEADERS_PIN_MAPPING_H */
